"use client";

import { FormEvent, useState } from "react";
import { Locale } from "./places";

const copy={
  es:{eyebrow:"NEGOCIOS LOCALES",title:"¿Tu servicio suma al viaje?",lede:"Postula tu cafetería, alojamiento, tour, tienda o experiencia. Revisamos calidad, información y utilidad antes de publicar: enviar no garantiza aparecer.",business:"Nombre del negocio",contact:"Persona de contacto",email:"Correo",phone:"Teléfono / WhatsApp",category:"Categoría",address:"Dirección",website:"Sitio o Instagram",languages:"Idiomas de atención",description:"Cuéntanos qué encuentra el viajero, horarios, precios y qué hace especial al lugar",send:"Enviar para revisión",sending:"Enviando…",success:"¡Solicitud recibida! La revisaremos antes de publicar.",privacy:"Tus datos se usan solo para revisar y contactar al negocio; no se publican automáticamente."},
  en:{eyebrow:"LOCAL BUSINESSES",title:"Does your service add to the trip?",lede:"Apply with your café, lodging, tour, shop or experience. We review quality, information and usefulness before publishing; submission does not guarantee listing.",business:"Business name",contact:"Contact person",email:"Email",phone:"Phone / WhatsApp",category:"Category",address:"Address",website:"Website or Instagram",languages:"Service languages",description:"Tell travellers what they will find, hours, prices and what makes the place special",send:"Send for review",sending:"Sending…",success:"Application received! We will review it before publishing.",privacy:"Your details are only used to review and contact the business; they are not published automatically."},
  pt:{eyebrow:"NEGÓCIOS LOCAIS",title:"Seu serviço melhora a viagem?",lede:"Inscreva seu café, hospedagem, tour, loja ou experiência. Revisamos qualidade e utilidade antes de publicar; o envio não garante inclusão.",business:"Nome do negócio",contact:"Pessoa de contato",email:"E-mail",phone:"Telefone / WhatsApp",category:"Categoria",address:"Endereço",website:"Site ou Instagram",languages:"Idiomas de atendimento",description:"Conte o que o viajante encontra, horários, preços e o diferencial",send:"Enviar para análise",sending:"Enviando…",success:"Solicitação recebida! Vamos revisar antes de publicar.",privacy:"Seus dados são usados apenas para análise e contato; não são publicados automaticamente."},
  fr:{eyebrow:"ENTREPRISES LOCALES",title:"Votre service enrichit le voyage ?",lede:"Proposez votre café, hébergement, visite, boutique ou expérience. Nous vérifions qualité et utilité avant publication ; l’envoi ne garantit pas l’ajout.",business:"Nom de l’entreprise",contact:"Personne à contacter",email:"E-mail",phone:"Téléphone / WhatsApp",category:"Catégorie",address:"Adresse",website:"Site ou Instagram",languages:"Langues d’accueil",description:"Décrivez ce que le voyageur trouvera, horaires, prix et particularités",send:"Envoyer pour examen",sending:"Envoi…",success:"Demande reçue ! Nous la vérifierons avant publication.",privacy:"Vos données servent uniquement à l’examen et au contact ; elles ne sont pas publiées automatiquement."}
};

export default function BusinessSignup({locale}:{locale:Locale}){
  const t=copy[locale], [status,setStatus]=useState(""),[sending,setSending]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSending(true);setStatus("");const form=new FormData(event.currentTarget);const languages=form.getAll("languages");const body=Object.fromEntries(form.entries());try{const response=await fetch("/api/business-applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,languages})});const data=await response.json();if(!response.ok)throw new Error(data.error);event.currentTarget.reset();setStatus(t.success)}catch(error){setStatus(error instanceof Error?error.message:"Error")}finally{setSending(false)}}
  return <section className="business-signup" id="negocios"><div className="section-heading"><p>{t.eyebrow}</p><h2>{t.title}</h2><span>{t.lede}</span></div><form onSubmit={submit}><label>{t.business}<input name="businessName" minLength={2} maxLength={100} required/></label><label>{t.contact}<input name="contactName" minLength={2} maxLength={80} required autoComplete="name"/></label><label>{t.email}<input name="email" type="email" autoComplete="email"/></label><label>{t.phone}<input name="phone" type="tel" autoComplete="tel"/></label><label>{t.category}<select name="category" required defaultValue=""><option value="" disabled>—</option><option>Cafetería / Restaurante</option><option>Alojamiento</option><option>Tour / Experiencia</option><option>Tienda / Growshop</option><option>Transporte</option><option>Cultura / Entretención</option><option>Otro</option></select></label><label>{t.address}<input name="address" minLength={5} maxLength={200} required autoComplete="street-address"/></label><label className="wide">{t.website}<input name="website" maxLength={200}/></label><fieldset className="wide"><legend>{t.languages}</legend>{["ES","EN","PT","FR"].map(language=><label key={language}><input type="checkbox" name="languages" value={language}/>{language}</label>)}</fieldset><label className="wide">{t.description}<textarea name="description" minLength={10} maxLength={600} rows={4} required/></label><label className="honeypot">Company website<input name="companyWebsite" tabIndex={-1}/></label><div className="business-submit wide"><small>{t.privacy}</small><button type="submit" disabled={sending}>{sending?t.sending:t.send}</button>{status&&<p role="status">{status}</p>}</div></form></section>;
}
