export type Locale = "es" | "en" | "pt" | "fr";
export type Category = "museum" | "coffee" | "food" | "view" | "stay" | "useful";

export type Place = {
  id: string;
  name: string;
  category: Category;
  rating: string;
  reviews?: string;
  coords: [number, number];
  neighborhood: string;
  visit: string;
  summary: Record<Locale, string>;
};

export const places: Place[] = [
  { id:"precolombino", name:"Museo Chileno de Arte Precolombino", category:"museum", rating:"4.7", reviews:"10.712", coords:[-33.43867,-70.65239], neighborhood:"Centro histórico", visit:"1,5–2 h", summary:{ es:"Piezas maestras de culturas americanas en un edificio histórico; ideal para entender Chile en contexto continental.", en:"Masterpieces from cultures across the Americas in a historic building; an excellent introduction to Chile in its continental context.", pt:"Obras-primas de culturas americanas em um edifício histórico; ótimo para entender o Chile no contexto continental.", fr:"Des chefs-d’œuvre des cultures américaines dans un bâtiment historique pour situer le Chili dans son contexte continental." } },
  { id:"memoria", name:"Museo de la Memoria y los Derechos Humanos", category:"museum", rating:"4.7", reviews:"14.724", coords:[-33.44010,-70.67954], neighborhood:"Quinta Normal", visit:"2–3 h", summary:{ es:"Museografía intensa y muy bien documentada sobre la dictadura, la memoria y los derechos humanos en Chile.", en:"A powerful, carefully documented museum about dictatorship, memory and human rights in Chile.", pt:"Museografia intensa e bem documentada sobre a ditadura, a memória e os direitos humanos no Chile.", fr:"Une muséographie forte et documentée sur la dictature, la mémoire et les droits humains au Chili." } },
  { id:"chascona", name:"La Chascona", category:"museum", rating:"4.6", reviews:"5.412", coords:[-33.43112,-70.63442], neighborhood:"Bellavista", visit:"1–1,5 h", summary:{ es:"La casa-museo de Pablo Neruda: objetos personales, arquitectura singular y visitas con cupos.", en:"Pablo Neruda’s house museum, filled with personal objects and distinctive architecture.", pt:"A casa-museu de Pablo Neruda, com objetos pessoais e arquitetura singular.", fr:"La maison-musée de Pablo Neruda, avec objets personnels et architecture singulière." } },
  { id:"cclm", name:"Centro Cultural La Moneda", category:"museum", rating:"4.6", reviews:"17.422", coords:[-33.44375,-70.65381], neighborhood:"Barrio Cívico", visit:"1–2 h", summary:{ es:"Exposiciones temporales, diseño y cine bajo la Plaza de la Ciudadanía; fácil de sumar al centro histórico.", en:"Temporary exhibitions, design and cinema beneath Plaza de la Ciudadanía; easy to pair with downtown.", pt:"Exposições temporárias, design e cinema sob a Plaza de la Ciudadanía; fácil de combinar com o centro.", fr:"Expositions temporaires, design et cinéma sous la Plaza de la Ciudadanía, au cœur du centre historique." } },
  { id:"singular", name:"Singular Coffee Roasters Lastarria", category:"coffee", rating:"4.6", reviews:"251", coords:[-33.43695,-70.64100], neighborhood:"Lastarria", visit:"30–60 min", summary:{ es:"Café de especialidad de tueste local, servicio rápido y ubicación práctica junto a Parque Forestal.", en:"Locally roasted specialty coffee, quick service and a handy location beside Parque Forestal.", pt:"Café especial torrado localmente, serviço rápido e localização prática junto ao Parque Forestal.", fr:"Café de spécialité torréfié localement, service rapide, près du Parque Forestal." } },
  { id:"3841", name:"3841 Coffee Roasters", category:"coffee", rating:"4.6", reviews:"435", coords:[-33.43827,-70.64127], neighborhood:"Lastarria", visit:"30–45 min", summary:{ es:"Barra pequeña enfocada en granos chilenos y latinoamericanos; buena parada breve en Lastarria.", en:"A compact bar focused on Chilean and Latin American beans; a smart short stop in Lastarria.", pt:"Barra pequena focada em grãos chilenos e latino-americanos; ótima parada rápida em Lastarria.", fr:"Petit comptoir consacré aux grains chiliens et latino-américains, parfait pour une pause à Lastarria." } },
  { id:"domestico", name:"Doméstico", category:"coffee", rating:"4.6", reviews:"1.246", coords:[-33.43994,-70.64091], neighborhood:"Lastarria", visit:"1–1,5 h", summary:{ es:"Café, brunch y pastelería en una casona de Lastarria, con ambiente relajado y mesas interiores.", en:"Coffee, brunch and pastries in a Lastarria townhouse with a relaxed atmosphere.", pt:"Café, brunch e confeitaria em um casarão de Lastarria, com ambiente descontraído.", fr:"Café, brunch et pâtisseries dans une maison de Lastarria à l’ambiance détendue." } },
  { id:"wonderland", name:"Wonderland Café", category:"coffee", rating:"4.5", reviews:"6.911", coords:[-33.43808,-70.64210], neighborhood:"Lastarria", visit:"1–1,5 h", summary:{ es:"Café temático y abundante, conocido por desayunos y brunch; suele tener espera en horas punta.", en:"A generous themed café known for breakfast and brunch; waits are common at peak times.", pt:"Café temático e farto, conhecido pelo café da manhã e brunch; pode haver fila nos horários de pico.", fr:"Café à thème réputé pour ses petits-déjeuners et brunchs copieux; attente possible aux heures de pointe." } },
  { id:"chilean-brunch", name:"Chilean Brunch", category:"food", rating:"4.8", reviews:"1.017", coords:[-33.43239,-70.63693], neighborhood:"Bellavista", visit:"1–1,5 h", summary:{ es:"Recetas chilenas en formato brunch, con porciones generosas y una carta fácil para quien llega por primera vez.", en:"Chilean recipes in brunch form, generous portions and an approachable menu for first-time visitors.", pt:"Receitas chilenas em formato brunch, porções generosas e um cardápio fácil para a primeira visita.", fr:"Recettes chiliennes façon brunch, portions généreuses et carte accessible pour une première visite." } },
  { id:"vivalavida", name:"Restaurant Viva La Vida", category:"food", rating:"4.8", reviews:"5.541", coords:[-33.43238,-70.63505], neighborhood:"Bellavista", visit:"1,5–2 h", summary:{ es:"Cocina chilena contemporánea, platos reconocibles, buena presentación y ambiente animado.", en:"Contemporary Chilean cooking with familiar dishes, polished presentation and a lively room.", pt:"Cozinha chilena contemporânea, com pratos conhecidos, boa apresentação e ambiente animado.", fr:"Cuisine chilienne contemporaine, plats familiers, présentation soignée et ambiance vivante." } },
  { id:"casa-lastarria", name:"Casa Lastarria", category:"food", rating:"4.7", reviews:"4.529", coords:[-33.43958,-70.64132], neighborhood:"Lastarria", visit:"1,5–2 h", summary:{ es:"Carta chilena e internacional en una esquina muy caminable; útil para almuerzo o cena sin salir del barrio.", en:"Chilean and international food on a very walkable corner; convenient for lunch or dinner nearby.", pt:"Cardápio chileno e internacional em uma esquina agradável; prático para almoçar ou jantar no bairro.", fr:"Carte chilienne et internationale à une adresse très accessible, idéale pour déjeuner ou dîner." } },
  { id:"chipe", name:"Chipe Libre", category:"food", rating:"4.6", reviews:"5.853", coords:[-33.43832,-70.64138], neighborhood:"Lastarria", visit:"1,5–2 h", summary:{ es:"Introducción entretenida al pisco de Chile y Perú, con degustaciones, coctelería y platos para compartir.", en:"A lively introduction to Chilean and Peruvian pisco with tastings, cocktails and shareable plates.", pt:"Uma introdução divertida ao pisco do Chile e do Peru, com degustações, coquetéis e pratos para compartilhar.", fr:"Une introduction ludique aux piscos chilien et péruvien, avec dégustations, cocktails et plats à partager." } },
  { id:"peumayen", name:"Peumayén Ancestral Food", category:"food", rating:"4.5", reviews:"1.918", coords:[-33.43282,-70.63502], neighborhood:"Bellavista", visit:"2–3 h", summary:{ es:"Menú inspirado en cocinas ancestrales de Chile; una experiencia gastronómica que conviene reservar.", en:"A menu inspired by Chile’s ancestral cuisines; a longer dining experience best booked ahead.", pt:"Menu inspirado nas cozinhas ancestrais do Chile; experiência mais longa, melhor com reserva.", fr:"Menu inspiré des cuisines ancestrales du Chili; une expérience gastronomique à réserver." } },
  { id:"san-cristobal", name:"Cerro San Cristóbal · Parquemet", category:"view", rating:"4.7", coords:[-33.42510,-70.63350], neighborhood:"Bellavista / Providencia", visit:"2–4 h", summary:{ es:"El gran paseo panorámico de Santiago: senderos, funicular, teleférico y vistas de la cordillera.", en:"Santiago’s signature panorama: trails, funicular, cable car and wide views of the Andes.", pt:"O grande passeio panorâmico de Santiago: trilhas, funicular, teleférico e vista dos Andes.", fr:"Le grand panorama de Santiago : sentiers, funiculaire, téléphérique et vue sur les Andes." } },
  { id:"sky", name:"Sky Costanera", category:"view", rating:"4.7", coords:[-33.41770,-70.60620], neighborhood:"Providencia", visit:"1–1,5 h", summary:{ es:"Mirador interior a 300 metros; funciona especialmente bien al atardecer si la visibilidad está despejada.", en:"An indoor observation deck 300 metres high; best near sunset when visibility is clear.", pt:"Mirante interno a 300 metros; ótimo no fim do dia quando a visibilidade está boa.", fr:"Belvédère intérieur à 300 mètres, idéal en fin de journée lorsque la visibilité est bonne." } },
  { id:"santa-lucia", name:"Cerro Santa Lucía", category:"view", rating:"4.6", coords:[-33.44053,-70.64347], neighborhood:"Lastarria", visit:"1–1,5 h", summary:{ es:"Jardines, escaleras históricas y un mirador céntrico; subida corta pero con varios peldaños.", en:"Gardens, historic stairways and a central viewpoint; a short climb with many steps.", pt:"Jardins, escadarias históricas e mirante central; subida curta com muitos degraus.", fr:"Jardins, escaliers historiques et belvédère central; montée courte mais riche en marches." } },
  { id:"bicentenario", name:"Parque Bicentenario", category:"view", rating:"4.8", coords:[-33.40110,-70.60620], neighborhood:"Vitacura", visit:"1–2 h", summary:{ es:"Parque amplio, cuidado y plano junto al río; perfecto para caminar, descansar o ir con niños.", en:"A spacious, polished and flat riverside park, ideal for walking, relaxing or visiting with children.", pt:"Parque amplo, bem cuidado e plano junto ao rio; perfeito para caminhar, descansar ou ir com crianças.", fr:"Grand parc plat et soigné au bord du fleuve, parfait pour marcher, se détendre ou venir en famille." } },
  { id:"magnolia", name:"Hotel Magnolia", category:"stay", rating:"4.7", coords:[-33.43920,-70.64370], neighborhood:"Lastarria", visit:"Estadía", summary:{ es:"Hotel boutique patrimonial cerca de Santa Lucía; ubicación fuerte para una primera visita cultural.", en:"A heritage boutique hotel near Santa Lucía, very well placed for a first cultural visit.", pt:"Hotel boutique histórico perto de Santa Lucía, muito bem localizado para a primeira visita.", fr:"Hôtel-boutique patrimonial près de Santa Lucía, très bien situé pour une première visite culturelle." } },
  { id:"solace", name:"Solace Hotel Santiago", category:"stay", rating:"4.6", coords:[-33.42120,-70.61070], neighborhood:"Providencia", visit:"Estadía", summary:{ es:"Base moderna y conectada a pasos del Metro Pedro de Valdivia, restaurantes y servicios.", en:"A modern, connected base close to Pedro de Valdivia Metro, restaurants and local services.", pt:"Base moderna e conectada perto do Metrô Pedro de Valdivia, restaurantes e serviços.", fr:"Base moderne et bien reliée près du métro Pedro de Valdivia et des services de Providencia." } },
  { id:"bidasoa", name:"Hotel Bidasoa", category:"stay", rating:"4.6", coords:[-33.39940,-70.58880], neighborhood:"Vitacura", visit:"Estadía", summary:{ es:"Hotel boutique tranquilo apreciado por su diseño, jardín, restaurantes y atención familiar.", en:"A quiet boutique hotel valued for design, garden, restaurants and warm service.", pt:"Hotel boutique tranquilo, reconhecido pelo design, jardim, restaurantes e atendimento acolhedor.", fr:"Hôtel-boutique paisible, apprécié pour son design, son jardin et son accueil." } },
  { id:"airport", name:"Transporte oficial Aeropuerto SCL", category:"useful", rating:"OFICIAL", coords:[-33.39300,-70.78580], neighborhood:"Aeropuerto", visit:"Al llegar", summary:{ es:"Mesones autorizados para buses, transfer y taxis. El punto seguro para decidir cómo llegar a la ciudad.", en:"Authorised desks for buses, transfers and taxis; the safe place to arrange your ride into the city.", pt:"Balcões autorizados para ônibus, transfer e táxis; o ponto seguro para organizar a ida à cidade.", fr:"Comptoirs autorisés pour bus, transferts et taxis : le point sûr pour rejoindre la ville." } },
  { id:"pajaritos", name:"Metro Pajaritos · conexión aeropuerto", category:"useful", rating:"CONEXIÓN", coords:[-33.45880,-70.71570], neighborhood:"Lo Prado", visit:"15–30 min", summary:{ es:"Intercambio práctico entre buses del aeropuerto y la Línea 1 del Metro hacia el centro y Providencia.", en:"A practical interchange between airport buses and Metro Line 1 toward downtown and Providencia.", pt:"Conexão prática entre os ônibus do aeroporto e a Linha 1 do Metrô rumo ao centro e Providencia.", fr:"Correspondance pratique entre les bus de l’aéroport et la ligne 1 du métro vers le centre et Providencia." } },
];
