export type Locale = "es" | "en" | "pt" | "fr";
export type Category = "museum" | "coffee" | "food" | "view" | "stay" | "useful" | "market" | "shop" | "experience" | "growshop";

export type Place = {
  id: string;
  name: string;
  category: Category;
  rating: string;
  reviews?: string;
  coords: [number, number];
  neighborhood: string;
  visit: string;
  summary: Record<Locale, string>;
};

export const places: Place[] = [
  { id:"precolombino", name:"Museo Chileno de Arte Precolombino", category:"museum", rating:"4.7", reviews:"10.712", coords:[-33.43867,-70.65239], neighborhood:"Centro histórico", visit:"1,5–2 h", summary:{ es:"Piezas maestras de culturas americanas en un edificio histórico; ideal para entender Chile en contexto continental.", en:"Masterpieces from cultures across the Americas in a historic building; an excellent introduction to Chile in its continental context.", pt:"Obras-primas de culturas americanas em um edifício histórico; ótimo para entender o Chile no contexto continental.", fr:"Des chefs-d’œuvre des cultures américaines dans un bâtiment historique pour situer le Chili dans son contexte continental." } },
  { id:"memoria", name:"Museo de la Memoria y los Derechos Humanos", category:"museum", rating:"4.7", reviews:"14.724", coords:[-33.44010,-70.67954], neighborhood:"Quinta Normal", visit:"2–3 h", summary:{ es:"Museografía intensa y muy bien documentada sobre la dictadura, la memoria y los derechos humanos en Chile.", en:"A powerful, carefully documented museum about dictatorship, memory and human rights in Chile.", pt:"Museografia intensa e bem documentada sobre a ditadura, a memória e os direitos humanos no Chile.", fr:"Une muséographie forte et documentée sur la dictature, la mémoire et les droits humains au Chili." } },
  { id:"chascona", name:"La Chascona", category:"museum", rating:"4.6", reviews:"5.412", coords:[-33.43112,-70.63442], neighborhood:"Bellavista", visit:"1–1,5 h", summary:{ es:"La casa-museo de Pablo Neruda: objetos personales, arquitectura singular y visitas con cupos.", en:"Pablo Neruda’s house museum, filled with personal objects and distinctive architecture.", pt:"A casa-museu de Pablo Neruda, com objetos pessoais e arquitetura singular.", fr:"La maison-musée de Pablo Neruda, avec objets personnels et architecture singulière." } },
  { id:"cclm", name:"Centro Cultural La Moneda", category:"museum", rating:"4.6", reviews:"17.422", coords:[-33.44375,-70.65381], neighborhood:"Barrio Cívico", visit:"1–2 h", summary:{ es:"Exposiciones temporales, diseño y cine bajo la Plaza de la Ciudadanía; fácil de sumar al centro histórico.", en:"Temporary exhibitions, design and cinema beneath Plaza de la Ciudadanía; easy to pair with downtown.", pt:"Exposições temporárias, design e cinema sob a Plaza de la Ciudadanía; fácil de combinar com o centro.", fr:"Expositions temporaires, design et cinéma sous la Plaza de la Ciudadanía, au cœur du centre historique." } },
  { id:"singular", name:"Singular Coffee Roasters Lastarria", category:"coffee", rating:"4.6", reviews:"251", coords:[-33.43695,-70.64100], neighborhood:"Lastarria", visit:"30–60 min", summary:{ es:"Café de especialidad de tueste local, servicio rápido y ubicación práctica junto a Parque Forestal.", en:"Locally roasted specialty coffee, quick service and a handy location beside Parque Forestal.", pt:"Café especial torrado localmente, serviço rápido e localização prática junto ao Parque Forestal.", fr:"Café de spécialité torréfié localement, service rapide, près du Parque Forestal." } },
  { id:"3841", name:"3841 Coffee Roasters", category:"coffee", rating:"4.6", reviews:"435", coords:[-33.43827,-70.64127], neighborhood:"Lastarria", visit:"30–45 min", summary:{ es:"Barra pequeña enfocada en granos chilenos y latinoamericanos; buena parada breve en Lastarria.", en:"A compact bar focused on Chilean and Latin American beans; a smart short stop in Lastarria.", pt:"Barra pequena focada em grãos chilenos e latino-americanos; ótima parada rápida em Lastarria.", fr:"Petit comptoir consacré aux grains chiliens et latino-américains, parfait pour une pause à Lastarria." } },
  { id:"domestico", name:"Doméstico", category:"coffee", rating:"4.6", reviews:"1.246", coords:[-33.43994,-70.64091], neighborhood:"Lastarria", visit:"1–1,5 h", summary:{ es:"Café, brunch y pastelería en una casona de Lastarria, con ambiente relajado y mesas interiores.", en:"Coffee, brunch and pastries in a Lastarria townhouse with a relaxed atmosphere.", pt:"Café, brunch e confeitaria em um casarão de Lastarria, com ambiente descontraído.", fr:"Café, brunch et pâtisseries dans une maison de Lastarria à l’ambiance détendue." } },
  { id:"wonderland", name:"Wonderland Café", category:"coffee", rating:"4.5", reviews:"6.911", coords:[-33.43808,-70.64210], neighborhood:"Lastarria", visit:"1–1,5 h", summary:{ es:"Café temático y abundante, conocido por desayunos y brunch; suele tener espera en horas punta.", en:"A generous themed café known for breakfast and brunch; waits are common at peak times.", pt:"Café temático e farto, conhecido pelo café da manhã e brunch; pode haver fila nos horários de pico.", fr:"Café à thème réputé pour ses petits-déjeuners et brunchs copieux; attente possible aux heures de pointe." } },
  { id:"chilean-brunch", name:"Chilean Brunch", category:"food", rating:"4.8", reviews:"1.017", coords:[-33.43239,-70.63693], neighborhood:"Bellavista", visit:"1–1,5 h", summary:{ es:"Recetas chilenas en formato brunch, con porciones generosas y una carta fácil para quien llega por primera vez.", en:"Chilean recipes in brunch form, generous portions and an approachable menu for first-time visitors.", pt:"Receitas chilenas em formato brunch, porções generosas e um cardápio fácil para a primeira visita.", fr:"Recettes chiliennes façon brunch, portions généreuses et carte accessible pour une première visite." } },
  { id:"vivalavida", name:"Restaurant Viva La Vida", category:"food", rating:"4.8", reviews:"5.541", coords:[-33.43238,-70.63505], neighborhood:"Bellavista", visit:"1,5–2 h", summary:{ es:"Cocina chilena contemporánea, platos reconocibles, buena presentación y ambiente animado.", en:"Contemporary Chilean cooking with familiar dishes, polished presentation and a lively room.", pt:"Cozinha chilena contemporânea, com pratos conhecidos, boa apresentação e ambiente animado.", fr:"Cuisine chilienne contemporaine, plats familiers, présentation soignée et ambiance vivante." } },
  { id:"casa-lastarria", name:"Casa Lastarria", category:"food", rating:"4.7", reviews:"4.529", coords:[-33.43958,-70.64132], neighborhood:"Lastarria", visit:"1,5–2 h", summary:{ es:"Carta chilena e internacional en una esquina muy caminable; útil para almuerzo o cena sin salir del barrio.", en:"Chilean and international food on a very walkable corner; convenient for lunch or dinner nearby.", pt:"Cardápio chileno e internacional em uma esquina agradável; prático para almoçar ou jantar no bairro.", fr:"Carte chilienne et internationale à une adresse très accessible, idéale pour déjeuner ou dîner." } },
  { id:"chipe", name:"Chipe Libre", category:"food", rating:"4.6", reviews:"5.853", coords:[-33.43832,-70.64138], neighborhood:"Lastarria", visit:"1,5–2 h", summary:{ es:"Introducción entretenida al pisco de Chile y Perú, con degustaciones, coctelería y platos para compartir.", en:"A lively introduction to Chilean and Peruvian pisco with tastings, cocktails and shareable plates.", pt:"Uma introdução divertida ao pisco do Chile e do Peru, com degustações, coquetéis e pratos para compartilhar.", fr:"Une introduction ludique aux piscos chilien et péruvien, avec dégustations, cocktails et plats à partager." } },
  { id:"peumayen", name:"Peumayén Ancestral Food", category:"food", rating:"4.5", reviews:"1.918", coords:[-33.43282,-70.63502], neighborhood:"Bellavista", visit:"2–3 h", summary:{ es:"Menú inspirado en cocinas ancestrales de Chile; una experiencia gastronómica que conviene reservar.", en:"A menu inspired by Chile’s ancestral cuisines; a longer dining experience best booked ahead.", pt:"Menu inspirado nas cozinhas ancestrais do Chile; experiência mais longa, melhor com reserva.", fr:"Menu inspiré des cuisines ancestrales du Chili; une expérience gastronomique à réserver." } },
  { id:"san-cristobal", name:"Cerro San Cristóbal · Parquemet", category:"view", rating:"4.7", coords:[-33.42510,-70.63350], neighborhood:"Bellavista / Providencia", visit:"2–4 h", summary:{ es:"El gran paseo panorámico de Santiago: senderos, funicular, teleférico y vistas de la cordillera.", en:"Santiago’s signature panorama: trails, funicular, cable car and wide views of the Andes.", pt:"O grande passeio panorâmico de Santiago: trilhas, funicular, teleférico e vista dos Andes.", fr:"Le grand panorama de Santiago : sentiers, funiculaire, téléphérique et vue sur les Andes." } },
  { id:"sky", name:"Sky Costanera", category:"view", rating:"4.7", coords:[-33.41770,-70.60620], neighborhood:"Providencia", visit:"1–1,5 h", summary:{ es:"Mirador interior a 300 metros; funciona especialmente bien al atardecer si la visibilidad está despejada.", en:"An indoor observation deck 300 metres high; best near sunset when visibility is clear.", pt:"Mirante interno a 300 metros; ótimo no fim do dia quando a visibilidade está boa.", fr:"Belvédère intérieur à 300 mètres, idéal en fin de journée lorsque la visibilité est bonne." } },
  { id:"santa-lucia", name:"Cerro Santa Lucía", category:"view", rating:"4.6", coords:[-33.44053,-70.64347], neighborhood:"Lastarria", visit:"1–1,5 h", summary:{ es:"Jardines, escaleras históricas y un mirador céntrico; subida corta pero con varios peldaños.", en:"Gardens, historic stairways and a central viewpoint; a short climb with many steps.", pt:"Jardins, escadarias históricas e mirante central; subida curta com muitos degraus.", fr:"Jardins, escaliers historiques et belvédère central; montée courte mais riche en marches." } },
  { id:"bicentenario", name:"Parque Bicentenario", category:"view", rating:"4.8", coords:[-33.40110,-70.60620], neighborhood:"Vitacura", visit:"1–2 h", summary:{ es:"Parque amplio, cuidado y plano junto al río; perfecto para caminar, descansar o ir con niños.", en:"A spacious, polished and flat riverside park, ideal for walking, relaxing or visiting with children.", pt:"Parque amplo, bem cuidado e plano junto ao rio; perfeito para caminhar, descansar ou ir com crianças.", fr:"Grand parc plat et soigné au bord du fleuve, parfait pour marcher, se détendre ou venir en famille." } },
  { id:"magnolia", name:"Hotel Magnolia", category:"stay", rating:"4.7", coords:[-33.43920,-70.64370], neighborhood:"Lastarria", visit:"Estadía", summary:{ es:"Hotel boutique patrimonial cerca de Santa Lucía; ubicación fuerte para una primera visita cultural.", en:"A heritage boutique hotel near Santa Lucía, very well placed for a first cultural visit.", pt:"Hotel boutique histórico perto de Santa Lucía, muito bem localizado para a primeira visita.", fr:"Hôtel-boutique patrimonial près de Santa Lucía, très bien situé pour une première visite culturelle." } },
  { id:"solace", name:"Solace Hotel Santiago", category:"stay", rating:"4.6", coords:[-33.42120,-70.61070], neighborhood:"Providencia", visit:"Estadía", summary:{ es:"Base moderna y conectada a pasos del Metro Pedro de Valdivia, restaurantes y servicios.", en:"A modern, connected base close to Pedro de Valdivia Metro, restaurants and local services.", pt:"Base moderna e conectada perto do Metrô Pedro de Valdivia, restaurantes e serviços.", fr:"Base moderne et bien reliée près du métro Pedro de Valdivia et des services de Providencia." } },
  { id:"bidasoa", name:"Hotel Bidasoa", category:"stay", rating:"4.6", coords:[-33.39940,-70.58880], neighborhood:"Vitacura", visit:"Estadía", summary:{ es:"Hotel boutique tranquilo apreciado por su diseño, jardín, restaurantes y atención familiar.", en:"A quiet boutique hotel valued for design, garden, restaurants and warm service.", pt:"Hotel boutique tranquilo, reconhecido pelo design, jardim, restaurantes e atendimento acolhedor.", fr:"Hôtel-boutique paisible, apprécié pour son design, son jardin et son accueil." } },
  { id:"airport", name:"Transporte oficial Aeropuerto SCL", category:"useful", rating:"OFICIAL", coords:[-33.39300,-70.78580], neighborhood:"Aeropuerto", visit:"Al llegar", summary:{ es:"Mesones autorizados para buses, transfer y taxis. El punto seguro para decidir cómo llegar a la ciudad.", en:"Authorised desks for buses, transfers and taxis; the safe place to arrange your ride into the city.", pt:"Balcões autorizados para ônibus, transfer e táxis; o ponto seguro para organizar a ida à cidade.", fr:"Comptoirs autorisés pour bus, transferts et taxis : le point sûr pour rejoindre la ville." } },
  { id:"pajaritos", name:"Metro Pajaritos · conexión aeropuerto", category:"useful", rating:"CONEXIÓN", coords:[-33.45880,-70.71570], neighborhood:"Lo Prado", visit:"15–30 min", summary:{ es:"Intercambio práctico entre buses del aeropuerto y la Línea 1 del Metro hacia el centro y Providencia.", en:"A practical interchange between airport buses and Metro Line 1 toward downtown and Providencia.", pt:"Conexão prática entre os ônibus do aeroporto e a Linha 1 do Metrô rumo ao centro e Providencia.", fr:"Correspondance pratique entre les bus de l’aéroport et la ligne 1 du métro vers le centre et Providencia." } },
  { id:"mercado-central", name:"Mercado Central de Santiago", category:"market", rating:"4.2", coords:[-33.43334,-70.65157], neighborhood:"Centro / Cal y Canto", visit:"1–2 h", summary:{ es:"Mercado patrimonial con pescaderías, artesanía y restaurantes de mariscos. Compara cartas y precios antes de sentarte.", en:"A heritage market with fishmongers, crafts and seafood restaurants. Compare menus and prices before choosing.", pt:"Mercado histórico com peixarias, artesanato e restaurantes de frutos do mar. Compare cardápios e preços.", fr:"Marché patrimonial avec poissonneries, artisanat et restaurants de fruits de mer. Comparez cartes et prix." } },
  { id:"vega-central", name:"La Vega Central", category:"market", rating:"4.4", coords:[-33.42955,-70.65045], neighborhood:"Recoleta", visit:"1,5–3 h", summary:{ es:"El gran mercado popular de alimentos de Santiago: frutas, verduras, cocinerías y vida local a precios cotidianos.", en:"Santiago’s major popular food market: produce, simple eateries and everyday local life.", pt:"O grande mercado popular de alimentos de Santiago: frutas, verduras, cozinhas e vida local.", fr:"Le grand marché alimentaire populaire de Santiago : produits frais, petites cantines et vie locale." } },
  { id:"tirso-molina", name:"Mercado Tirso de Molina", category:"market", rating:"4.3", coords:[-33.43132,-70.64917], neighborhood:"Recoleta", visit:"1–2 h", summary:{ es:"Mercado de abastos con cocinerías chilenas y latinoamericanas en el segundo piso; muy usado por residentes.", en:"A produce market with Chilean and Latin American kitchens upstairs, widely used by locals.", pt:"Mercado de abastecimento com cozinhas chilenas e latino-americanas no segundo andar.", fr:"Marché de produits frais avec cuisines chiliennes et latino-américaines à l’étage." } },
  { id:"persa-biobio", name:"Persa Biobío", category:"market", rating:"4.4", coords:[-33.47822,-70.64245], neighborhood:"Franklin", visit:"3–5 h", summary:{ es:"Miles de puestos de antigüedades, diseño, vinilos, tecnología y cocinerías. Su mejor ambiente suele ser el fin de semana.", en:"Thousands of antiques, design, vinyl, tech and food stalls; weekends usually have the liveliest atmosphere.", pt:"Milhares de bancas de antiguidades, design, vinis, tecnologia e comida; melhor nos fins de semana.", fr:"Des milliers de stands d’antiquités, design, vinyles, technologie et cuisine; idéal le week-end." } },
  { id:"mut", name:"MUT · Mercado Urbano Tobalaba", category:"market", rating:"4.6", coords:[-33.41815,-70.60155], neighborhood:"Las Condes / Tobalaba", visit:"1,5–3 h", summary:{ es:"Mercado urbano conectado al Metro Tobalaba, con restaurantes, tiendas, servicios y espacios de descanso.", en:"An urban market connected to Tobalaba Metro with restaurants, shops, services and places to relax.", pt:"Mercado urbano conectado ao Metrô Tobalaba, com restaurantes, lojas, serviços e áreas de descanso.", fr:"Marché urbain relié au métro Tobalaba, avec restaurants, boutiques, services et espaces de repos." } },
  { id:"los-dominicos", name:"Centro Artesanal Los Dominicos", category:"market", rating:"4.5", coords:[-33.40747,-70.53402], neighborhood:"Las Condes", visit:"2–3 h", summary:{ es:"Talleres y tiendas de artesanía chilena en un entorno tradicional junto al Metro Los Dominicos.", en:"Chilean craft workshops and shops in a traditional setting beside Los Dominicos Metro.", pt:"Oficinas e lojas de artesanato chileno em ambiente tradicional junto ao Metrô Los Dominicos.", fr:"Ateliers et boutiques d’artisanat chilien dans un cadre traditionnel près du métro Los Dominicos." } },
  { id:"costanera-center", name:"Cenco Costanera", category:"shop", rating:"4.4", coords:[-33.41724,-70.60633], neighborhood:"Providencia", visit:"2–5 h", summary:{ es:"Centro comercial de gran escala con tiendas, gastronomía, supermercado y acceso directo a Sky Costanera.", en:"A large shopping centre with retail, dining, supermarket and direct access to Sky Costanera.", pt:"Grande shopping com lojas, gastronomia, supermercado e acesso direto ao Sky Costanera.", fr:"Grand centre commercial avec boutiques, restauration, supermarché et accès direct à Sky Costanera." } },
  { id:"parque-arauco", name:"Parque Arauco", category:"shop", rating:"4.5", coords:[-33.40260,-70.57840], neighborhood:"Las Condes", visit:"2–5 h", summary:{ es:"Compras, restaurantes, cine y entretenimiento familiar junto al Parque Araucano; práctico para una tarde completa.", en:"Shopping, restaurants, cinema and family entertainment beside Parque Araucano.", pt:"Compras, restaurantes, cinema e entretenimento familiar junto ao Parque Araucano.", fr:"Shopping, restaurants, cinéma et loisirs familiaux près du Parque Araucano." } },
  { id:"drugstore", name:"Drugstore Providencia", category:"shop", rating:"4.4", coords:[-33.42455,-70.61050], neighborhood:"Providencia", visit:"1–2 h", summary:{ es:"Galería comercial clásica con diseño chileno, moda independiente, librerías, cafés y tiendas pequeñas.", en:"A classic shopping gallery for Chilean design, independent fashion, books, cafés and small shops.", pt:"Galeria comercial clássica com design chileno, moda independente, livrarias, cafés e pequenas lojas.", fr:"Galerie commerçante classique : design chilien, mode indépendante, librairies, cafés et petites boutiques." } },
  { id:"patio-bellavista", name:"Patio Bellavista", category:"shop", rating:"4.4", coords:[-33.43270,-70.63420], neighborhood:"Bellavista", visit:"1,5–3 h", summary:{ es:"Conjunto de restaurantes, bares, artesanía y tiendas; cómodo para grupos y para combinar con La Chascona.", en:"A cluster of restaurants, bars, crafts and shops, convenient for groups and a visit to La Chascona.", pt:"Conjunto de restaurantes, bares, artesanato e lojas; prático para grupos e para visitar La Chascona.", fr:"Ensemble de restaurants, bars, artisanat et boutiques, pratique avec une visite de La Chascona." } },
  { id:"turistik", name:"Turistik · Hop On Hop Off", category:"experience", rating:"4.4", coords:[-33.41756,-70.60641], neighborhood:"Providencia", visit:"Medio día", summary:{ es:"Operador de buses turísticos y excursiones desde Santiago; revisa recorridos, horarios y punto de salida antes de comprar.", en:"A sightseeing bus and excursion operator; confirm routes, schedules and departure point before booking.", pt:"Operador de ônibus turísticos e excursões; confirme rotas, horários e ponto de saída antes de comprar.", fr:"Opérateur de bus touristiques et d’excursions ; vérifiez parcours, horaires et départ avant réservation." } },
  { id:"andoandes", name:"AndoAndes · Tours de montaña", category:"experience", rating:"4.8", coords:[-33.43620,-70.61580], neighborhood:"Providencia", visit:"Día completo", summary:{ es:"Excursiones guiadas a cordillera, Cajón del Maipo y nieve. Confirma nivel físico, clima y equipamiento incluido.", en:"Guided trips to the Andes, Cajón del Maipo and snow; confirm fitness level, weather and included gear.", pt:"Excursões guiadas à cordilheira, Cajón del Maipo e neve; confirme nível físico, clima e equipamento.", fr:"Excursions guidées dans les Andes, au Cajón del Maipo et dans la neige ; vérifiez niveau et équipement." } },
  { id:"vinolia", name:"Vinolia", category:"experience", rating:"4.6", coords:[-33.40205,-70.58917], neighborhood:"Vitacura", visit:"1,5–2,5 h", summary:{ es:"Experiencia urbana de vinos chilenos con degustaciones y contenido audiovisual; buena alternativa sin salir de Santiago.", en:"An urban Chilean wine experience with tastings and audiovisual content, without leaving Santiago.", pt:"Experiência urbana de vinhos chilenos com degustações e conteúdo audiovisual, sem sair de Santiago.", fr:"Expérience urbaine autour des vins chiliens, avec dégustations et contenu audiovisuel, sans quitter Santiago." } },
  { id:"teatro-municipal", name:"Teatro Municipal de Santiago", category:"experience", rating:"4.7", coords:[-33.44018,-70.64718], neighborhood:"Centro histórico", visit:"2–3 h", summary:{ es:"Ópera, ballet, conciertos y visitas patrimoniales en uno de los principales escenarios culturales de Chile.", en:"Opera, ballet, concerts and heritage tours at one of Chile’s leading cultural venues.", pt:"Ópera, balé, concertos e visitas patrimoniais em um dos principais palcos culturais do Chile.", fr:"Opéra, ballet, concerts et visites patrimoniales dans l’une des grandes scènes culturelles du Chili." } },
  { id:"fantasilandia", name:"Fantasilandia", category:"experience", rating:"4.5", coords:[-33.46335,-70.66088], neighborhood:"Parque O'Higgins", visit:"4–7 h", summary:{ es:"Parque de diversiones para familias y grupos; revisa calendario, estatura mínima y compra anticipada.", en:"An amusement park for families and groups; check calendar, height requirements and advance tickets.", pt:"Parque de diversões para famílias e grupos; confira calendário, altura mínima e ingressos antecipados.", fr:"Parc d’attractions pour familles et groupes ; vérifiez calendrier, taille minimale et billets à l’avance." } },
  { id:"delaferia-providencia", name:"Delaferia Growshop Manuel Montt", category:"growshop", rating:"4.5", reviews:"43", coords:[-33.42920,-70.61935], neighborhood:"Providencia · Manuel Montt 043", visit:"20–45 min", summary:{ es:"Tienda física de cultivo indoor, hidroponía, iluminación y accesorios. Atención adulta; verifica normativa y stock antes de ir.", en:"A physical shop for indoor growing, hydroponics, lighting and accessories. Adults only; check local rules and stock.", pt:"Loja física de cultivo indoor, hidroponia, iluminação e acessórios. Atendimento adulto; confira normas e estoque.", fr:"Boutique physique de culture indoor, hydroponie, éclairage et accessoires. Public adulte ; vérifiez règles et stock." } },
  { id:"semillas-huaso-providencia", name:"Semillas del Huaso Providencia", category:"growshop", rating:"5.0", reviews:"398", coords:[-33.42508,-70.61340], neighborhood:"Providencia · Av. Providencia 1998, local 5", visit:"20–45 min", summary:{ es:"Growshop junto al Metro Pedro de Valdivia con semillas, insumos y accesorios. Compra responsable y solo para adultos.", en:"A grow shop by Pedro de Valdivia Metro with seeds, supplies and accessories. Responsible adult shopping only.", pt:"Growshop junto ao Metrô Pedro de Valdivia com sementes, insumos e acessórios. Compra responsável para adultos.", fr:"Growshop près du métro Pedro de Valdivia avec graines, fournitures et accessoires. Achat responsable réservé aux adultes." } },
  { id:"fumetas-providencia", name:"Fumetas Store Providencia", category:"growshop", rating:"DESTACADO", coords:[-33.42386,-70.60810], neighborhood:"Providencia · Av. Providencia 2198, local 6", visit:"20–45 min", summary:{ es:"Smoke shop y growshop en Portal Lyon, con vaporizadores, accesorios y retiro de compras online. Solo adultos.", en:"A smoke and grow shop in Portal Lyon with vaporizers, accessories and online pickup. Adults only.", pt:"Smoke shop e growshop no Portal Lyon, com vaporizadores, acessórios e retirada online. Somente adultos.", fr:"Smoke shop et growshop au Portal Lyon, avec vaporisateurs, accessoires et retrait en ligne. Réservé aux adultes." } },
  { id:"savia-growshop", name:"Savia Growshop", category:"growshop", rating:"NEGOCIO LOCAL", coords:[-33.43915,-70.59620], neighborhood:"Providencia · Suecia 2561", visit:"20–45 min", summary:{ es:"Centro de retiro con insumos de cultivo, nutrientes y semillas. Confirma horario de atención y disponibilidad antes de visitar.", en:"A pickup point for growing supplies, nutrients and seeds. Confirm opening hours and availability before visiting.", pt:"Centro de retirada de insumos de cultivo, nutrientes e sementes. Confirme horário e disponibilidade.", fr:"Point de retrait pour matériel de culture, nutriments et graines. Confirmez horaires et disponibilité." } },
  { id:"coffee-cure-maipu", name:"Coffee Cure", category:"coffee", rating:"NEGOCIO LOCAL", coords:[-33.50970,-70.75665], neighborhood:"Maipú · Avenida Maipú 036", visit:"45–90 min", summary:{ es:"Cafetería familiar de especialidad frente al edificio consistorial, con libros, arte maipucino y ambiente de barrio.", en:"A family-run specialty café opposite the municipal building, with books, local art and a neighborhood atmosphere.", pt:"Cafeteria familiar de especialidade em frente à prefeitura, com livros, arte local e ambiente de bairro.", fr:"Café familial de spécialité face à la mairie, avec livres, art local et ambiance de quartier." } },
  { id:"coffee-culture-maipu", name:"Coffee Culture Coffee Roasters", category:"coffee", rating:"4.8", reviews:"738", coords:[-33.51020,-70.75525], neighborhood:"Maipú · General Ordóñez 199", visit:"45–90 min", summary:{ es:"Tostaduría y cafetería pionera de Maipú, conocida por café de especialidad, granos de origen, libros y pastelería.", en:"A pioneering Maipú roastery and café known for specialty coffee, single-origin beans, books and pastries.", pt:"Torrefação e cafeteria pioneira de Maipú, conhecida por cafés especiais, grãos de origem, livros e confeitaria.", fr:"Torréfaction et café pionnier de Maipú, réputé pour ses cafés de spécialité, livres et pâtisseries." } },
  { id:"cahve-maipu", name:"Cafetería Cahve", category:"coffee", rating:"4.7", reviews:"747", coords:[-33.50755,-70.76125], neighborhood:"Maipú · Primera Transversal 2227", visit:"45–90 min", summary:{ es:"Café filtrado, brunch, sándwiches y pastelería en una casa con espacios interiores y jardín.", en:"Filter coffee, brunch, sandwiches and pastries in a house with indoor seating and a garden.", pt:"Café filtrado, brunch, sanduíches e confeitaria em uma casa com salão e jardim.", fr:"Café filtre, brunch, sandwichs et pâtisseries dans une maison avec salle et jardin." } },
  { id:"murta-maipu", name:"Murta Cafetería", category:"coffee", rating:"4.7", reviews:"248", coords:[-33.52520,-70.74570], neighborhood:"Maipú · José Luis Infante Larraín 1446", visit:"45–90 min", summary:{ es:"Cafetería de barrio con brunch, sándwiches, postres y actividades culturales; cuenta con opciones familiares y accesibles.", en:"A neighborhood café serving brunch, sandwiches and desserts, with cultural events and accessible family seating.", pt:"Cafeteria de bairro com brunch, sanduíches, sobremesas e atividades culturais; ambiente familiar e acessível.", fr:"Café de quartier avec brunch, sandwichs, desserts et activités culturelles ; cadre familial et accessible." } },
  { id:"pura-vida-cerrillos", name:"Pura Vida Puro Café", category:"coffee", rating:"NEGOCIO LOCAL", coords:[-33.50360,-70.70990], neighborhood:"Cerrillos · Av. Américo Vespucio 2701", visit:"30–75 min", summary:{ es:"Alternativa de café de barrio en Cerrillos para una pausa fuera del circuito del sector oriente.", en:"A neighborhood coffee option in Cerrillos for a break beyond Santiago’s eastern districts.", pt:"Opção de café de bairro em Cerrillos para uma pausa fora do circuito da zona leste.", fr:"Option café de quartier à Cerrillos, loin du circuit des quartiers de l’est." } },
  { id:"bonafide-cerrillos", name:"Bonafide Mall Plaza Oeste", category:"coffee", rating:"CADENA", coords:[-33.51655,-70.71615], neighborhood:"Cerrillos · Av. Américo Vespucio 1501, local D-149", visit:"30–75 min", summary:{ es:"Cafetería práctica dentro de Mall Plaza Oeste, con café, bollería y horario extendido para compras o trámites.", en:"A convenient café inside Mall Plaza Oeste with coffee, pastries and extended shopping-centre hours.", pt:"Cafeteria prática no Mall Plaza Oeste, com café, confeitaria e horário amplo.", fr:"Café pratique dans le Mall Plaza Oeste, avec café, viennoiseries et horaires étendus." } },
  { id:"san-camilo-terminal", name:"San Camilo · Terminal Tur Bus", category:"coffee", rating:"PRÁCTICO", coords:[-33.45255,-70.68895], neighborhood:"Estación Central · Alameda 3750", visit:"15–45 min", summary:{ es:"Panadería-cafetería útil para desayunar o esperar una salida de bus dentro del principal eje de terminales.", en:"A practical bakery café for breakfast or waiting for a bus in Santiago’s main terminal district.", pt:"Padaria-cafeteria prática para tomar café da manhã ou esperar o ônibus na zona dos terminais.", fr:"Boulangerie-café pratique pour déjeuner ou attendre un bus dans le quartier des terminaux." } },
  { id:"san-camilo-paseo-estacion", name:"San Camilo · Paseo Estación", category:"coffee", rating:"PRÁCTICO", coords:[-33.45115,-70.67995], neighborhood:"Estación Central · San Francisco de Borja 84", visit:"20–60 min", summary:{ es:"Cafetería y panadería dentro de Paseo Estación, conveniente para viajeros de tren, Metro y Terminal San Borja.", en:"A café and bakery inside Paseo Estación, convenient for train, Metro and San Borja terminal passengers.", pt:"Cafeteria e padaria no Paseo Estación, prática para passageiros de trem, metrô e Terminal San Borja.", fr:"Café-boulangerie dans Paseo Estación, pratique pour les voyageurs du train, métro et terminal San Borja." } },
];
