"use client";

import { useEffect, useState } from "react";
import { Locale } from "./places";
import { currencyOptions, formatTravelMoney, RatesResponse } from "./travel-money";

type Fare={key:"red"|"airportBus"|"shortRide"|"airportRide"|"rental";min:number;max:number;kind:"official"|"estimate";official?:string};
const fares:Fare[]=[
  {key:"red",min:735,max:895,official:"https://www.red.cl/tarifas-y-recargas/conoce-las-tarifas/",kind:"official"},
  {key:"airportBus",min:2400,max:2400,official:"https://www.centropuerto.cl/centro-faq",kind:"official"},
  {key:"shortRide",min:4500,max:10000,kind:"estimate"},
  {key:"airportRide",min:20000,max:35000,official:"https://www.nuevopudahuel.cl/transporte-oficial",kind:"estimate"},
  {key:"rental",min:35000,max:70000,kind:"estimate"},
];

const copy={
  es:{eyebrow:"MUÉVETE SIN PAGAR DE MÁS",title:"Precios de transporte y guía antiestafas",lede:"Compara antes de subir. Las tarifas oficiales están identificadas; taxi, aplicación y arriendo son rangos razonables que cambian por tráfico, demanda, peajes y proveedor.",currency:"Mostrar en",red:"Bus, Metro o Tren Nos",redNote:"Pasaje integrado por hasta 120 minutos. Bus $795; Metro/Tren $735–$895 según horario.",airportBus:"Bus Centropuerto · aeropuerto",airportBusNote:"$2.400 solo ida; ida y vuelta publicada en $4.100. Conserva el ticket.",shortRide:"Taxi o aplicación · trayecto urbano corto",shortRideNote:"Referencia para unos 3–8 km en condiciones normales. Revisa el total en pantalla antes de confirmar.",airportRide:"Aeropuerto → Centro o Providencia",airportRideNote:"Rango orientativo por vehículo. En hora punta o alta demanda puede subir.",rental:"Arriendo de auto · por día",rentalNote:"Solo vehículo económico; agrega combustible, TAG/peajes, estacionamiento y seguro.",official:"Tarifa oficial",estimate:"Estimación SOS",perTrip:"por viaje",perDay:"por día",safe:"Antes de pagar",tips:["En el aeropuerto compra solo en módulos oficiales o usa la aplicación elegida; no aceptes ofertas de personas en el pasillo.","Pide precio total, destino y comprobante antes de abordar. El sistema VOT del aeropuerto entrega estimación y voucher digital.","En aplicación verifica patente, nombre y foto. No cambies el viaje a efectivo si no quieres.","Si el cobro supera claramente el rango, pide explicación por peajes o demanda y compara otra opción."],updated:"Referencias revisadas el 23 sep 2026. Confirma el valor final antes de viajar."},
  en:{eyebrow:"MOVE WITHOUT OVERPAYING",title:"Transport prices and scam prevention",lede:"Compare before boarding. Official fares are identified; taxi, ride-hailing and rental figures are reasonable ranges that vary with traffic, demand, tolls and provider.",currency:"Show in",red:"Bus, Metro or Tren Nos",redNote:"Integrated fare for up to 120 minutes. Bus CLP 795; Metro/Train CLP 735–895 by time.",airportBus:"Centropuerto airport bus",airportBusNote:"CLP 2,400 one way; published return CLP 4,100. Keep your ticket.",shortRide:"Taxi or app · short city ride",shortRideNote:"Reference for roughly 3–8 km in normal conditions. Check the total before confirming.",airportRide:"Airport → Downtown or Providencia",airportRideNote:"Indicative range per vehicle. Peak traffic or surge pricing can increase it.",rental:"Car rental · per day",rentalNote:"Economy vehicle only; add fuel, tolls, parking and insurance.",official:"Official fare",estimate:"SOS estimate",perTrip:"per trip",perDay:"per day",safe:"Before paying",tips:["At the airport buy only at official counters or use your chosen app; ignore hallway solicitors.","Ask for total price, destination and receipt before boarding. The airport VOT system provides an estimate and digital voucher.","In an app verify plate, driver name and photo. Do not switch to cash unless you choose to.","If the charge clearly exceeds the range, ask about tolls or surge and compare another option."],updated:"References checked 23 Sep 2026. Confirm the final price before travelling."},
  pt:{eyebrow:"DESLOQUE-SE SEM PAGAR DEMAIS",title:"Preços de transporte e guia antifraudes",lede:"Compare antes de embarcar. Tarifas oficiais estão marcadas; táxi, aplicativo e aluguel são faixas que variam com trânsito, demanda, pedágios e fornecedor.",currency:"Mostrar em",red:"Ônibus, Metrô ou Tren Nos",redNote:"Tarifa integrada por até 120 minutos. Ônibus CLP 795; Metrô/Trem CLP 735–895 conforme horário.",airportBus:"Ônibus Centropuerto · aeroporto",airportBusNote:"CLP 2.400 só ida; ida e volta publicada CLP 4.100. Guarde o bilhete.",shortRide:"Táxi ou aplicativo · trajeto curto",shortRideNote:"Referência para cerca de 3–8 km em condições normais. Confira o total antes de confirmar.",airportRide:"Aeroporto → Centro ou Providencia",airportRideNote:"Faixa por veículo. Horário de pico ou alta demanda pode elevar o valor.",rental:"Aluguel de carro · por dia",rentalNote:"Só veículo econômico; some combustível, pedágios, estacionamento e seguro.",official:"Tarifa oficial",estimate:"Estimativa SOS",perTrip:"por viagem",perDay:"por dia",safe:"Antes de pagar",tips:["No aeroporto compre somente nos balcões oficiais ou use o aplicativo escolhido; ignore ofertas no corredor.","Peça preço total, destino e comprovante antes de embarcar. O sistema VOT fornece estimativa e voucher digital.","No aplicativo confira placa, nome e foto. Não mude para dinheiro se não quiser.","Se a cobrança superar muito a faixa, pergunte sobre pedágios ou demanda e compare outra opção."],updated:"Referências verificadas em 23 set 2026. Confirme o preço final."},
  fr:{eyebrow:"DÉPLACEZ-VOUS SANS SURPAYER",title:"Prix des transports et prévention des arnaques",lede:"Comparez avant de monter. Les tarifs officiels sont signalés ; taxi, application et location sont des fourchettes variant selon trafic, demande, péages et prestataire.",currency:"Afficher en",red:"Bus, Métro ou Tren Nos",redNote:"Tarif intégré pendant 120 minutes. Bus 795 CLP ; Métro/Train 735–895 CLP selon l’heure.",airportBus:"Bus Centropuerto · aéroport",airportBusNote:"2 400 CLP aller ; aller-retour publié à 4 100 CLP. Gardez le billet.",shortRide:"Taxi ou application · court trajet",shortRideNote:"Référence pour environ 3–8 km en conditions normales. Vérifiez le total avant de confirmer.",airportRide:"Aéroport → Centre ou Providencia",airportRideNote:"Fourchette par véhicule. Trafic de pointe ou forte demande peuvent l’augmenter.",rental:"Location de voiture · par jour",rentalNote:"Véhicule économique seul ; ajoutez carburant, péages, parking et assurance.",official:"Tarif officiel",estimate:"Estimation SOS",perTrip:"par trajet",perDay:"par jour",safe:"Avant de payer",tips:["À l’aéroport, achetez uniquement aux comptoirs officiels ou utilisez l’application choisie ; refusez les sollicitations dans le hall.","Demandez prix total, destination et reçu avant de monter. Le système VOT fournit estimation et reçu numérique.","Dans l’application, vérifiez plaque, nom et photo. Ne passez pas en espèces sans le vouloir.","Si le montant dépasse nettement la fourchette, demandez le détail des péages ou de la demande et comparez."],updated:"Références vérifiées le 23 sept. 2026. Confirmez le prix final."}
};

export default function TransportGuide({locale,currency,onCurrencyChange}:{locale:Locale;currency:string;onCurrencyChange:(currency:string)=>void}){
  const t=copy[locale];const [rates,setRates]=useState<RatesResponse|null>(null);
  useEffect(()=>{fetch("/api/rates").then(response=>response.ok?response.json():Promise.reject()).then(setRates).catch(()=>setRates(null))},[]);
  return <section className="transport-guide" id="transporte"><div className="transport-head"><div className="section-heading"><p>{t.eyebrow}</p><h2>{t.title}</h2><span>{t.lede}</span></div><label>{t.currency}<select value={currency} onChange={event=>onCurrencyChange(event.target.value)}>{currencyOptions.map(([code,name])=><option value={code} key={code}>{name} · {code}</option>)}</select></label></div><div className="fare-grid">{fares.map(fare=><article key={fare.key}><span className={fare.kind}>{fare.kind==="official"?t.official:t.estimate}</span><h3>{t[fare.key]}</h3><strong>{formatTravelMoney(fare.min,currency,locale,rates?.rates??null)}{fare.max!==fare.min&&<> – {formatTravelMoney(fare.max,currency,locale,rates?.rates??null)}</>}</strong><small>{fare.key==="rental"?t.perDay:t.perTrip}</small><p>{t[`${fare.key}Note` as keyof typeof t]}</p>{fare.official&&<a href={fare.official} target="_blank" rel="noreferrer">{t.official} ↗</a>}</article>)}</div><div className="anti-scam"><div><b>✓</b><h3>{t.safe}</h3></div><ol>{t.tips.map(tip=><li key={tip}>{tip}</li>)}</ol><small>{t.updated}</small></div></section>;
}
