import { useEffect, useState } from "react";
import { Locale } from "./places";
import { currencyOptions, formatTravelMoney, RatesResponse } from "./travel-money";

type Fare={key:"red"|"airportBus"|"shortRide"|"airportRide"|"rental";min:number;max:number;kind:"official"|"estimate";official?:string};
const fares:Fare[]=[
  {key:"red",min:735,max:895,official:"https://www.red.cl/tarifas-y-recargas/conoce-las-tarifas/",kind:"official"},
  {key:"airportBus",min:2400,max:2400,official:"https://www.centropuerto.cl/centro-faq",kind:"official"},
  {key:"shortRide",min:4500,max:10000,kind:"estimate"},
  {key:"airportRide",min:20000,max:35000,official:"https://www.nuevopudahuel.cl/transporte-oficial",kind:"estimate"},
  {key:"rental",min:35000,max:70000,kind:"estimate"},
];

const copy={
  es:{eyebrow:"MUÉVETE SIN PAGAR DE MÁS",title:"Precios de transporte y guía antiestafas",lede:"Compara antes de subir. Las tarifas oficiales están identificadas; taxi, aplicación y arriendo son rangos razonables que cambian por tráfico, demanda, peajes y proveedor.",currency:"Mostrar en",red:"Bus, Metro o Tren Nos",redNote:"Pasaje integrado por hasta 120 minutos. Bus $795; Metro/Tren $735–$895 según horario.",airportBus:"Bus Centropuerto · aeropuerto",airportBusNote:"$2.400 solo ida; ida y vuelta publicada en $4.100. Conserva el ticket.",shortRide:"Taxi o aplicación · trayecto urbano corto",shortRideNote:"Referencia para unos 3–8 km en condiciones normales. Revisa el total en pantalla antes de confirmar.",airportRide:"Aeropuerto → Centro o Providencia",airportRideNote:"Rango orientativo por vehículo. En hora punta o alta demanda puede subir.",rental:"Arriendo de auto · por día",rentalNote:"Solo vehículo económico; agrega combustible, TAG/peajes, estacionamiento y seguro.",official:"Tarifa oficial",estimate:"Estimación SOS",perTrip:"por viaje",perDay:"por día",safe:"Antes de pagar",tips:["En el aeropuerto compra solo en módulos oficiales o usa la aplicación elegida; no aceptes ofertas de personas en el pasillo.","Pide precio total, destino y comprobante antes de abordar. El sistema VOT del aeropuerto entrega estimación y voucher digital.","En aplicación verifica patente, nombre y foto. No cambies el viaje a efectivo si no quieres.","Si el cobro supera claramente el rango, pide explicación por peajes o demanda y compara otra opción."],updated:"Referencias revisadas el 23 sep 2026. Confirma el valor final antes de viajar."},
  en:{eyebrow:"MOVE WITHOUT OVERPAYING",title:"Transport prices and scam prevention",lede:"Compare before boarding. Official fares are identified; taxi, ride-hailing and rental figures are reasonable ranges that vary with traffic, demand, tolls and provider.",currency:"Show in",red:"Bus, Metro or Tren Nos",redNote:"Integrated fare for up to 120 minutes. Bus CLP 795; Metro/Train CLP 735–895 by time.",airportBus:"Centropuerto airport bus",airportBusNote:"CLP 2,400 one way; published return CLP 4,100. Keep your ticket.",shortRide:"Taxi or app · short city ride",shortRideNote:"Reference for roughly 3–8 km in normal conditions. Check the total before confirming.",airportRide:"Airport → Downtown or Providencia",airportRideNote:"Indicative range per vehicle. Peak traffic or surge pricing can increase it.",rental:"Car rental · per day",rentalNote:"Economy vehicle only; add fuel, tolls, parking and insurance.",official:"Official fare",estimate:"SOS estimate",perTrip:"per trip",perDay:"per day",safe:"Before paying",tips:["At the airport buy only at official counters or use your chosen app; ignore hallway solicitors.","Ask for total price, destination and receipt before boarding. The airport VOT system provides an estimate and digital voucher.","In an app verify plate, driver name and photo. Do not switch to cash unless you choose to.","If the charge clearly exceeds the range, ask about tolls or surge and compare another option."],updated:"References checked 23 Sep 2026. Confirm the final price before travelling."},
  pt:{eyebrow:"DESLOQUE-SE SEM PAGAR DEMAIS",title:"Preços de transporte e guia antifraudes",lede:"Compare antes de embarcar. Tarifas oficiais estão marcadas; táxi, aplicativo e aluguel são faixas que variam com trânsito, demanda, pedágios e fornecedor.",currency:"Mostrar em",red:"Ônibus, Metrô ou Tren Nos",redNote:"Tarifa integrada por até 120 minutos. Ônibus CLP 795; Metrô/Trem CLP 735–895 conforme horário.",airportBus:"Ônibus Centropuerto · aeroporto",airportBusNote:"CLP 2.400 só ida; ida e volta publicada CLP 4.100. Guarde o bilhete.",shortRide:"Táxi ou aplicativo · trajeto curto",shortRideNote:"Referência para cerca de 3–8 km em condições normais. Confira o total antes de confirmar.",airportRide:"Aeroporto → Centro ou Providencia",airportRideNote:"Faixa por veículo. Horário de pico ou alta demanda pode elevar o valor.",rental:"Aluguel de carro · por dia",rentalNote:"Só veículo econômico; some combustível, pedágios, estacionamento e seguro.",official:"Tarifa oficial",estimate:"Estimativa SOS",perTrip:"por viagem",perDay:"por dia",safe:"Antes de pagar",tips:["No aeroporto compre somente nos balcões oficiais ou use o aplicativo escolhido; ignore ofertas no corredor.","Peça preço total, destino e comprovante antes de embarcar. O sistema VOT fornece estimativa e voucher digital.","No aplicativo confira placa, nome e foto. Não mude para dinheiro se não quiser.","Se a cobrança superar muito a faixa, pergunte sobre pedágios ou demanda e compare outra opção."],updated:"Referências verificadas em 23 set 2026. Confirme o preço final."},
  fr:{eyebrow:"DÉPLACEZ-VOUS SANS SURPAYER",title:"Prix des transports et prévention des arnaques",lede:"Comparez avant de monter. Les tarifs officiels sont signalés ; taxi, application et location sont des fourchettes variant selon trafic, demande, péages et prestataire.",currency:"Afficher en",red:"Bus, Métro ou Tren Nos",redNote:"Tarif intégré pendant 120 minutes. Bus 795 CLP ; Métro/Train 735–895 CLP selon l’heure.",airportBus:"Bus Centropuerto · aéroport",airportBusNote:"2 400 CLP aller ; aller-retour publié à 4 100 CLP. Gardez le billet.",shortRide:"Taxi ou application · court trajet",shortRideNote:"Référence pour environ 3–8 km en conditions normales. Vérifiez le total avant de confirmer.",airportRide:"Aéroport → Centre ou Providencia",airportRideNote:"Fourchette par véhicule. Trafic de pointe ou forte demande peuvent l’augmenter.",rental:"Location de voiture · par jour",rentalNote:"Véhicule économique seul ; ajoutez carburant, péages, parking et assurance.",official:"Tarif officiel",estimate:"Estimation SOS",perTrip:"par trajet",perDay:"par jour",safe:"Avant de payer",tips:["À l’aéroport, achetez uniquement aux comptoirs officiels ou utilisez l’application choisie ; refusez les sollicitations dans le hall.","Demandez prix total, destination et reçu avant de monter. Le système VOT fournit estimation et reçu numérique.","Dans l’application, vérifiez plaque, nom et photo. Ne passez pas en espèces sans le vouloir.","Si le montant dépasse nettement la fourchette, demandez le détail des péages ou de la demande et comparez."],updated:"Références vérifiées le 23 sept. 2026. Confirmez le prix final."}
};

// Metro adult fares in CLP by period (tarjetabip.cl, in force since 22 Feb 2026). Weekends and holidays are charged as "valle" all day.
const metroPeriods=[{key:"peak",clp:895,hours:"07:00–08:59 · 18:00–19:59"},{key:"mid",clp:815,hours:"09:00–17:59 · 20:00–20:44"},{key:"low",clp:735,hours:"06:00–06:59 · 20:45–23:00"}] as const;
const METRO_URL="https://www.metro.cl/",BIP_URL="https://www.tarjetabip.cl/tarifas.php";
const metroCopy:Record<Locale,{title:string;lede:string;peak:string;mid:string;low:string;facts:string[];map:string;official:string;fares:string}>={
  es:{title:"Metro para viajeros",lede:"Siete líneas cubren casi todos los atractivos de Santiago. El precio depende de la hora en que pasas el torniquete, de lunes a viernes.",peak:"Punta",mid:"Valle",low:"Bajo",facts:["Funciona aprox. de 6:00 a 23:00 (sábado desde las 6:30; domingo y festivos desde las 8:00). El último tren cambia según la estación.","Se paga con tarjeta bip!, que se compra y carga en las boleterías de cualquier estación. No se paga en efectivo en el torniquete.","Sábados, domingos y festivos se cobra tarifa valle todo el día.","Durante 120 minutos puedes combinar con bus pagando solo la diferencia, con un máximo de dos transbordos.","El Metro no llega al aeropuerto: baja en Pajaritos o Los Héroes (Línea 1) y sigue en el bus Centropuerto."],map:"Ver líneas en el mapa",official:"Sitio oficial de Metro",fares:"Tarifas oficiales"},
  en:{title:"Metro for travellers",lede:"Seven lines reach almost every attraction in Santiago. On weekdays the fare depends on the time you pass the turnstile.",peak:"Peak",mid:"Off-peak",low:"Low",facts:["Runs roughly 6:00 to 23:00 (Saturdays from 6:30; Sundays and holidays from 8:00). The last train varies by station.","You pay with a bip! card, sold and topped up at any station ticket office. Cash is not accepted at the turnstile.","Saturdays, Sundays and holidays are charged at the off-peak fare all day.","For 120 minutes you can transfer to a bus paying only the difference, with a maximum of two transfers.","The Metro does not reach the airport: get off at Pajaritos or Los Héroes (Line 1) and continue on the Centropuerto bus."],map:"See the lines on the map",official:"Official Metro site",fares:"Official fares"},
  pt:{title:"Metrô para viajantes",lede:"Sete linhas chegam a quase todas as atrações de Santiago. De segunda a sexta, o preço depende da hora em que você passa a catraca.",peak:"Pico",mid:"Normal",low:"Baixo",facts:["Funciona aprox. das 6:00 às 23:00 (sábado a partir das 6:30; domingo e feriados a partir das 8:00). O último trem varia conforme a estação.","Paga-se com o cartão bip!, vendido e recarregado nas bilheterias de qualquer estação. Não se paga em dinheiro na catraca.","Sábados, domingos e feriados têm tarifa normal o dia todo.","Durante 120 minutos você pode integrar com ônibus pagando só a diferença, com no máximo duas integrações.","O metrô não chega ao aeroporto: desça em Pajaritos ou Los Héroes (Linha 1) e siga no ônibus Centropuerto."],map:"Ver linhas no mapa",official:"Site oficial do Metrô",fares:"Tarifas oficiais"},
  fr:{title:"Le métro pour les voyageurs",lede:"Sept lignes desservent presque tous les sites de Santiago. En semaine, le tarif dépend de l’heure de passage au tourniquet.",peak:"Pointe",mid:"Normal",low:"Creux",facts:["Circule d’environ 6 h à 23 h (samedi dès 6 h 30 ; dimanche et jours fériés dès 8 h). Le dernier train varie selon la station.","On paie avec la carte bip!, vendue et rechargée aux guichets de toutes les stations. Pas d’espèces au tourniquet.","Samedis, dimanches et jours fériés : tarif normal toute la journée.","Pendant 120 minutes, la correspondance avec le bus ne coûte que la différence, avec deux correspondances au maximum.","Le métro ne va pas à l’aéroport : descendez à Pajaritos ou Los Héroes (ligne 1) puis prenez le bus Centropuerto."],map:"Voir les lignes sur la carte",official:"Site officiel du métro",fares:"Tarifs officiels"},
};

type Partner={id:number;name:string;phone?:string;whatsapp?:string;url?:string;languages:string[];note?:Record<Locale,string>;active?:boolean};
// Shown while a partner has "Estoy atendiendo" switched on in their panel (it expires by itself).
const activeCopy:Record<Locale,string>={es:"Disponible ahora",en:"Available now",pt:"Disponível agora",fr:"Disponible maintenant"};
const taxiCopy:Record<Locale,{title:string;lede:string;badge:string;call:string;site:string;empty:string;join:string}>={
  es:{title:"Radio taxis colaboradores",lede:"Empresas que SOS Travellers contactó y verificó. Pide siempre el precio total antes de subir.",badge:"Colaborador",call:"Llamar",site:"Sitio web",empty:"Estamos verificando empresas de radio taxi y transfer antes de recomendarlas aquí. Mientras tanto, usa los módulos oficiales del aeropuerto o tu aplicación habitual.",join:"¿Tienes una empresa de radio taxi o transfer? Súmate"},
  en:{title:"Partner radio taxis",lede:"Companies SOS Travellers has contacted and verified. Always ask for the total price before boarding.",badge:"Partner",call:"Call",site:"Website",empty:"We are verifying radio taxi and transfer companies before recommending them here. Meanwhile, use the official airport counters or your usual app.",join:"Run a radio taxi or transfer company? Join us"},
  pt:{title:"Rádio táxis parceiros",lede:"Empresas que a SOS Travellers contatou e verificou. Peça sempre o preço total antes de embarcar.",badge:"Parceiro",call:"Ligar",site:"Site",empty:"Estamos verificando empresas de rádio táxi e transfer antes de recomendá-las aqui. Enquanto isso, use os balcões oficiais do aeroporto ou seu aplicativo habitual.",join:"Tem uma empresa de rádio táxi ou transfer? Participe"},
  fr:{title:"Radio-taxis partenaires",lede:"Entreprises contactées et vérifiées par SOS Travellers. Demandez toujours le prix total avant de monter.",badge:"Partenaire",call:"Appeler",site:"Site web",empty:"Nous vérifions des entreprises de radio-taxi et de transfert avant de les recommander ici. En attendant, utilisez les comptoirs officiels de l’aéroport ou votre application habituelle.",join:"Vous gérez une entreprise de radio-taxi ou de transfert ? Rejoignez-nous"},
};
const digits=(value:string)=>value.replace(/[^\d+]/g,"");

export default function TransportGuide({locale,currency,onCurrencyChange,onShowMetro}:{locale:Locale;currency:string;onCurrencyChange:(currency:string)=>void;onShowMetro:()=>void}){
  const t=copy[locale],mt=metroCopy[locale],xt=taxiCopy[locale];const [rates,setRates]=useState<RatesResponse|null>(null);const [partners,setPartners]=useState<Partner[]>([]);
  useEffect(()=>{fetch("/api/rates").then(response=>response.ok?response.json():Promise.reject()).then(setRates).catch(()=>setRates(null))},[]);
  useEffect(()=>{fetch("/api/partners?kind=radio_taxi&region=RM").then(response=>response.ok?response.json():Promise.reject()).then((data:{partners?:Partner[]})=>setPartners(data.partners??[])).catch(()=>setPartners([]))},[]);
  return <section className="transport-guide" id="transporte"><div className="transport-head"><div className="section-heading"><p>{t.eyebrow}</p><h2>{t.title}</h2><span>{t.lede}</span></div><label>{t.currency}<select value={currency} onChange={event=>onCurrencyChange(event.target.value)}>{currencyOptions.map(([code,name])=><option value={code} key={code}>{name} · {code}</option>)}</select></label></div><div className="fare-grid">{fares.map(fare=><article key={fare.key}><span className={fare.kind}>{fare.kind==="official"?t.official:t.estimate}</span><h3>{t[fare.key]}</h3><strong>{formatTravelMoney(fare.min,currency,locale,rates?.rates??null)}{fare.max!==fare.min&&<> – {formatTravelMoney(fare.max,currency,locale,rates?.rates??null)}</>}</strong><small>{fare.key==="rental"?t.perDay:t.perTrip}</small><p>{t[`${fare.key}Note` as keyof typeof t]}</p>{fare.official&&<a href={fare.official} target="_blank" rel="noreferrer">{t.official} ↗</a>}</article>)}</div>
    <div className="metro-info" id="metro"><div className="metro-info-head"><h3>{mt.title}</h3><p>{mt.lede}</p><div className="metro-links"><button type="button" onClick={onShowMetro}>▣ {mt.map}</button><a href={METRO_URL} target="_blank" rel="noreferrer">{mt.official} ↗</a><a href={BIP_URL} target="_blank" rel="noreferrer">{mt.fares} ↗</a></div></div><div className="metro-periods">{metroPeriods.map(period=><div key={period.key} className={period.key}><b>{mt[period.key]}</b><strong>{formatTravelMoney(period.clp,currency,locale,rates?.rates??null)}</strong><small>{period.hours}</small></div>)}</div><ul>{mt.facts.map(fact=><li key={fact}>{fact}</li>)}</ul></div>
    <div className="taxi-partners" id="radio-taxi"><div><h3>{xt.title}</h3><p>{partners.length?xt.lede:xt.empty}</p></div>{partners.length>0&&<div className="taxi-grid">{partners.map(partner=><article key={partner.id}><span>{xt.badge}</span>{partner.active&&<em className="taxi-active">{activeCopy[locale]}</em>}<b>{partner.name}</b>{partner.note?.[locale]&&<p>{partner.note[locale]}</p>}{partner.languages.length>0&&<small>{partner.languages.join(" · ")}</small>}<div>{partner.phone&&<a href={`tel:${digits(partner.phone)}`}>☎ {xt.call}</a>}{partner.whatsapp&&<a href={`https://wa.me/${digits(partner.whatsapp).replace("+","")}`} target="_blank" rel="sponsored noopener noreferrer">WhatsApp ↗</a>}{partner.url&&<a href={partner.url} target="_blank" rel="sponsored noopener noreferrer">{xt.site} ↗</a>}</div></article>)}</div>}<a className="taxi-join" href="#negocios">{xt.join} →</a></div>
    <div className="anti-scam"><div><b>✓</b><h3>{t.safe}</h3></div><ol>{t.tips.map(tip=><li key={tip}>{tip}</li>)}</ol><small>{t.updated}</small></div></section>;
}
