import { FormEvent, useEffect, useState } from "react";
import { Locale } from "./places";
import { currencyOptions } from "./travel-money";

export type ConnectivityChoice = "roaming"|"esim"|"local_sim"|"wifi"|"need_help";
export type TravelInterest = "culture"|"food"|"nature"|"free"|"views"|"nightlife"|"shopping"|"wine"|"snow"|"family";
export type TravellerProfile = {
  partySize:number; adults:number; children:number; tripDays:number; connectivity:ConnectivityChoice; interests:TravelInterest[];
  budget:"free"|"low"|"medium"|"flexible"; pace:"relaxed"|"balanced"|"intense";
  preferredTime:"morning"|"afternoon"|"evening"|"any"; transport:"walk"|"public"|"car"|"mixed"; avoidStairs:boolean;
};

const interestIcons:Record<TravelInterest,string>={culture:"▣",food:"◉",nature:"♧",free:"$0",views:"⌁",nightlife:"♪",shopping:"◇",wine:"♨",snow:"❄",family:"☺"};
const interests=Object.keys(interestIcons) as TravelInterest[];

const copy={
  es:{eyebrow:"TU VIAJE, TUS REGLAS",title:"Preparemos tu guía",lede:"Responde solo preferencias de viaje. No necesitamos saber quién eres.",language:"Idioma",currency:"Moneda",group:"Tu grupo",adults:"Adultos",children:"Niños",days:"Días en Santiago",style:"¿Qué te gustaría conocer?",culture:"Cultura y museos",food:"Comida y cafeterías",nature:"Parques y naturaleza",free:"Panoramas gratis",views:"Vistas y fotografía",nightlife:"Vida nocturna",shopping:"Compras y mercados",wine:"Viñas",snow:"Nieve y cordillera",family:"Actividades familiares",budgetTitle:"Presupuesto por día",budget_free:"Solo gratis",budget_low:"Económico",budget_medium:"Intermedio",budget_flexible:"Flexible",paceTitle:"Ritmo del viaje",pace_relaxed:"Tranquilo",pace_balanced:"Equilibrado",pace_intense:"Quiero aprovechar todo",timeTitle:"Horario preferido",time_morning:"Mañana",time_afternoon:"Tarde",time_evening:"Noche",time_any:"Cualquiera",transportTitle:"Cómo prefieres moverte",transport_walk:"Caminando",transport_public:"Transporte público",transport_car:"Auto",transport_mixed:"Combinado",access:"Prefiero rutas con menos escaleras",accessNote:"Esta preferencia queda solo en este dispositivo.",internet:"Internet en Chile",roaming:"Roaming",esim:"eSIM",local_sim:"Chip chileno",wifi:"Solo Wi-Fi",need_help:"Necesito orientación",anonymous:"Compartir estas preferencias de forma anónima para mejorar SOS Travellers.",privacy:"La guía funciona sin compartir datos. Nunca solicitamos nombre, documento, teléfono, datos médicos, pago ni ubicación permanente.",send:"Crear mis recomendaciones",sending:"Preparando…",skip:"Ver la página sin encuesta",edit:"Mis preferencias",success:"¡Listo! Ya preparamos panoramas para ti.",error:"Tu guía quedó guardada en este dispositivo, pero no pudimos enviar las estadísticas anónimas.",chooseInterest:"Selecciona al menos un interés."},
  en:{eyebrow:"YOUR TRIP, YOUR RULES",title:"Let’s prepare your guide",lede:"Answer travel preferences only. We do not need to know who you are.",language:"Language",currency:"Currency",group:"Your group",adults:"Adults",children:"Children",days:"Days in Santiago",style:"What would you like to discover?",culture:"Culture and museums",food:"Food and coffee",nature:"Parks and nature",free:"Free activities",views:"Views and photography",nightlife:"Nightlife",shopping:"Shopping and markets",wine:"Wineries",snow:"Snow and mountains",family:"Family activities",budgetTitle:"Daily budget",budget_free:"Free only",budget_low:"Low cost",budget_medium:"Mid-range",budget_flexible:"Flexible",paceTitle:"Travel pace",pace_relaxed:"Relaxed",pace_balanced:"Balanced",pace_intense:"Make the most of it",timeTitle:"Preferred time",time_morning:"Morning",time_afternoon:"Afternoon",time_evening:"Evening",time_any:"Any",transportTitle:"How you prefer to get around",transport_walk:"Walking",transport_public:"Public transport",transport_car:"Car",transport_mixed:"Mixed",access:"I prefer routes with fewer stairs",accessNote:"This preference stays on this device only.",internet:"Internet in Chile",roaming:"Roaming",esim:"eSIM",local_sim:"Chilean SIM",wifi:"Wi-Fi only",need_help:"I need guidance",anonymous:"Share these preferences anonymously to improve SOS Travellers.",privacy:"The guide works without sharing data. We never request your name, ID, phone, medical, payment or permanent location data.",send:"Create my recommendations",sending:"Preparing…",skip:"Browse without the survey",edit:"My preferences",success:"Ready! We prepared activities for you.",error:"Your guide is saved on this device, but anonymous statistics could not be sent.",chooseInterest:"Select at least one interest."},
  pt:{eyebrow:"SUA VIAGEM, SUAS REGRAS",title:"Vamos preparar seu guia",lede:"Responda apenas preferências de viagem. Não precisamos saber quem você é.",language:"Idioma",currency:"Moeda",group:"Seu grupo",adults:"Adultos",children:"Crianças",days:"Dias em Santiago",style:"O que gostaria de conhecer?",culture:"Cultura e museus",food:"Comida e cafeterias",nature:"Parques e natureza",free:"Passeios grátis",views:"Vistas e fotografia",nightlife:"Vida noturna",shopping:"Compras e mercados",wine:"Vinícolas",snow:"Neve e cordilheira",family:"Atividades familiares",budgetTitle:"Orçamento diário",budget_free:"Somente grátis",budget_low:"Econômico",budget_medium:"Intermediário",budget_flexible:"Flexível",paceTitle:"Ritmo da viagem",pace_relaxed:"Tranquilo",pace_balanced:"Equilibrado",pace_intense:"Quero aproveitar tudo",timeTitle:"Horário preferido",time_morning:"Manhã",time_afternoon:"Tarde",time_evening:"Noite",time_any:"Qualquer",transportTitle:"Como prefere se locomover",transport_walk:"Caminhando",transport_public:"Transporte público",transport_car:"Carro",transport_mixed:"Combinado",access:"Prefiro rotas com menos escadas",accessNote:"Esta preferência fica somente neste dispositivo.",internet:"Internet no Chile",roaming:"Roaming",esim:"eSIM",local_sim:"Chip chileno",wifi:"Somente Wi-Fi",need_help:"Preciso de orientação",anonymous:"Compartilhar estas preferências anonimamente para melhorar a SOS Travellers.",privacy:"O guia funciona sem compartilhar dados. Nunca pedimos nome, documento, telefone, dados médicos, pagamento ou localização permanente.",send:"Criar minhas recomendações",sending:"Preparando…",skip:"Ver a página sem pesquisa",edit:"Minhas preferências",success:"Pronto! Preparamos passeios para você.",error:"Seu guia está salvo neste dispositivo, mas não foi possível enviar estatísticas anônimas.",chooseInterest:"Selecione pelo menos um interesse."},
  fr:{eyebrow:"VOTRE VOYAGE, VOS RÈGLES",title:"Préparons votre guide",lede:"Répondez uniquement sur vos préférences. Nous n’avons pas besoin de savoir qui vous êtes.",language:"Langue",currency:"Devise",group:"Votre groupe",adults:"Adultes",children:"Enfants",days:"Jours à Santiago",style:"Que souhaitez-vous découvrir ?",culture:"Culture et musées",food:"Cuisine et cafés",nature:"Parcs et nature",free:"Activités gratuites",views:"Vues et photographie",nightlife:"Vie nocturne",shopping:"Shopping et marchés",wine:"Vignobles",snow:"Neige et montagne",family:"Activités familiales",budgetTitle:"Budget quotidien",budget_free:"Gratuit uniquement",budget_low:"Économique",budget_medium:"Intermédiaire",budget_flexible:"Flexible",paceTitle:"Rythme du voyage",pace_relaxed:"Tranquille",pace_balanced:"Équilibré",pace_intense:"Profiter au maximum",timeTitle:"Horaire préféré",time_morning:"Matin",time_afternoon:"Après-midi",time_evening:"Soir",time_any:"Tous",transportTitle:"Mode de déplacement préféré",transport_walk:"À pied",transport_public:"Transport public",transport_car:"Voiture",transport_mixed:"Combiné",access:"Je préfère les parcours avec moins d’escaliers",accessNote:"Cette préférence reste uniquement sur cet appareil.",internet:"Internet au Chili",roaming:"Itinérance",esim:"eSIM",local_sim:"SIM chilienne",wifi:"Wi-Fi uniquement",need_help:"J’ai besoin de conseils",anonymous:"Partager anonymement ces préférences pour améliorer SOS Travellers.",privacy:"Le guide fonctionne sans partager de données. Nous ne demandons jamais nom, pièce d’identité, téléphone, données médicales, paiement ou position permanente.",send:"Créer mes recommandations",sending:"Préparation…",skip:"Continuer sans questionnaire",edit:"Mes préférences",success:"Prêt ! Nous avons préparé des activités pour vous.",error:"Votre guide est enregistré sur cet appareil, mais les statistiques anonymes n’ont pas été envoyées.",chooseInterest:"Sélectionnez au moins un centre d’intérêt."}
};

export default function TravellerWelcome({locale,onLocaleChange,currency,onCurrencyChange,onProfile}:{locale:Locale;onLocaleChange:(value:Locale)=>void;currency:string;onCurrencyChange:(value:string)=>void;onProfile:(profile:TravellerProfile|null)=>void}){
  const [open,setOpen]=useState(false),[sending,setSending]=useState(false),[status,setStatus]=useState("");
  const t=copy[locale];
  useEffect(()=>{localStorage.removeItem("sos-traveller-profile");const completed=localStorage.getItem("sos-welcome-v2"),saved=localStorage.getItem("sos-traveller-profile-v2");queueMicrotask(()=>{if(saved)try{onProfile(JSON.parse(saved) as TravellerProfile)}catch{}if(!completed)setOpen(true)})},[onProfile]);
  function close(){localStorage.setItem("sos-welcome-v2","done");setOpen(false)}
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setSending(true);setStatus("");const form=new FormData(event.currentTarget);const selectedInterests=form.getAll("interests") as TravelInterest[];
    if(!selectedInterests.length){setStatus(t.chooseInterest);setSending(false);return}
    const adults=Number(form.get("adults")),children=Number(form.get("children"));
    const profile:TravellerProfile={adults,children,partySize:adults+children,tripDays:Number(form.get("tripDays")),connectivity:String(form.get("connectivity")) as ConnectivityChoice,interests:selectedInterests,budget:String(form.get("budget")) as TravellerProfile["budget"],pace:String(form.get("pace")) as TravellerProfile["pace"],preferredTime:String(form.get("preferredTime")) as TravellerProfile["preferredTime"],transport:String(form.get("transport")) as TravellerProfile["transport"],avoidStairs:form.get("avoidStairs")==="yes"};
    localStorage.setItem("sos-traveller-profile-v2",JSON.stringify(profile));onProfile(profile);localStorage.setItem("sos-welcome-v2","done");
    if(form.get("anonymousConsent")==="yes")try{const response=await fetch("/api/traveller-profiles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...profile,preferredLanguage:locale,preferredCurrency:currency,anonymousConsent:true,companyWebsite:form.get("companyWebsite")})});if(!response.ok)throw new Error()}catch{setStatus(t.error);setSending(false);setTimeout(()=>setOpen(false),1200);return}
    setStatus(t.success);setSending(false);setTimeout(()=>{setOpen(false);document.getElementById("para-ti")?.scrollIntoView({behavior:"smooth"})},700);
  }
  const radio=(legend:string,name:string,values:string[],defaultValue:string,prefix:string)=><fieldset className="survey-options"><legend>{legend}</legend>{values.map(value=><label key={value}><input type="radio" name={name} value={value} defaultChecked={value===defaultValue}/><span>{String(t[`${prefix}_${value}` as keyof typeof t])}</span></label>)}</fieldset>;
  return <><button className="traveller-reopen" type="button" onClick={()=>setOpen(true)}>✦ {t.edit}</button>{open&&<div className="welcome-overlay" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><div className="welcome-card survey-card"><div className="welcome-brand"><img src="/assets/sos-logo-v2.png" alt="SOS Travellers · Just Enjoy"/><div><p>{t.eyebrow}</p><h2 id="welcome-title">{t.title}</h2><span>{t.lede}</span></div></div><form onSubmit={submit}>
    <div className="welcome-preferences"><label>{t.language}<select value={locale} onChange={event=>onLocaleChange(event.target.value as Locale)}><option value="es">Español</option><option value="en">English</option><option value="pt">Português</option><option value="fr">Français</option></select></label><label>{t.currency}<select value={currency} onChange={event=>onCurrencyChange(event.target.value)}>{currencyOptions.map(([code,name])=><option key={code} value={code}>{code} · {name}</option>)}</select></label></div>
    <h3 className="survey-section-title">1 · {t.group}</h3><div className="welcome-grid compact"><label>{t.adults}<input name="adults" type="number" min="1" max="20" defaultValue="1" required/></label><label>{t.children}<input name="children" type="number" min="0" max="12" defaultValue="0" required/></label><label>{t.days}<input name="tripDays" type="number" min="1" max="90" defaultValue="5" required/></label></div>
    <fieldset className="interest-choice"><legend>2 · {t.style}</legend>{interests.map(value=><label key={value}><input type="checkbox" name="interests" value={value}/><span><i>{interestIcons[value]}</i>{t[value]}</span></label>)}</fieldset>
    <div className="survey-preferences">{radio(t.budgetTitle,"budget",["free","low","medium","flexible"],"low","budget")}{radio(t.paceTitle,"pace",["relaxed","balanced","intense"],"balanced","pace")}{radio(t.timeTitle,"preferredTime",["morning","afternoon","evening","any"],"any","time")}{radio(t.transportTitle,"transport",["walk","public","car","mixed"],"mixed","transport")}</div>
    <label className="local-preference"><input type="checkbox" name="avoidStairs" value="yes"/><span>{t.access}<small>{t.accessNote}</small></span></label>
    <fieldset className="connectivity-choice"><legend>{t.internet}</legend>{(["roaming","esim","local_sim","wifi","need_help"] as ConnectivityChoice[]).map((value,index)=><label key={value}><input type="radio" name="connectivity" value={value} defaultChecked={index===4}/><span>{t[value]}</span></label>)}</fieldset>
    <div className="privacy-panel"><b>🔒 {t.privacy}</b><label><input type="checkbox" name="anonymousConsent" value="yes"/><span>{t.anonymous}</span></label></div><label className="honeypot">Company website<input name="companyWebsite" tabIndex={-1}/></label>
    <div className="welcome-actions"><button type="button" onClick={close}>{t.skip}</button><button type="submit" disabled={sending}>{sending?t.sending:t.send}</button></div>{status&&<p className="welcome-status" role="status">{status}</p>}
  </form></div></div>}</>;
}
