create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  place_id text not null check (place_id ~ '^[a-z0-9-]{2,64}$'),
  author_name text not null check (char_length(author_name) between 2 and 40),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 5 and 400),
  status text not null default 'published' check (status in ('published', 'hidden')),
  created_at timestamptz not null default now()
);

create index if not exists reviews_place_created_idx
  on public.reviews (place_id, created_at desc)
  where status = 'published';

alter table public.reviews enable row level security;

grant usage on schema public to service_role;
grant select, insert on table public.reviews to service_role;
grant usage, select on sequence public.reviews_id_seq to service_role;

comment on table public.reviews is 'Opiniones de viajeros publicadas en SOS Travellers.';
