create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 2 and 140),
  venue text not null check (char_length(venue) between 2 and 120),
  category text not null default 'other' check (category in ('concert','circus','theatre','festival','fair','sport','party','other')),
  region text not null check (region in ('AP','TA','AN','AT','CO','VS','RM','LI','ML','NB','BI','AR','LR','LL','AI','MA')),
  lat double precision check (lat between -57 and -17),
  lng double precision check (lng between -110 and -66),
  starts_at timestamptz not null,
  ends_at timestamptz,
  price_label text,
  url text,
  summary jsonb,
  featured boolean not null default false,
  status text not null default 'published' check (status in ('published','hidden')),
  created_at timestamptz not null default now()
);

create index if not exists events_region_starts_idx on public.events (region, starts_at) where status = 'published';

alter table public.events enable row level security;
grant usage on schema public to service_role;
grant insert, select, update, delete on public.events to service_role;
grant usage, select on sequence public.events_id_seq to service_role;
comment on table public.events is 'Eventos de los próximos días. featured = evento destacado (pagado). summary es {es,en,pt,fr}.';
