create table if not exists public.traveller_profiles (
  id bigint generated by default as identity primary key,
  first_name text not null check (char_length(first_name) between 2 and 60),
  last_name text not null check (char_length(last_name) between 2 and 60),
  nationality text not null check (char_length(nationality) between 2 and 80),
  residence_country text not null check (char_length(residence_country) between 2 and 80),
  adults smallint not null check (adults between 1 and 30),
  children smallint not null check (children between 0 and 20),
  trip_days smallint not null check (trip_days between 1 and 365),
  arrival_date date,
  connectivity text not null check (connectivity in ('roaming','esim','local_sim','wifi','need_help')),
  preferred_language text not null check (preferred_language in ('es','en','pt','fr')),
  preferred_currency text not null check (preferred_currency in ('CLP','ARS','BRL','USD','EUR','PEN','COP','UYU','GBP','CAD','MXN','AUD')),
  consent_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists traveller_profiles_created_idx on public.traveller_profiles (created_at desc);
alter table public.traveller_profiles enable row level security;
grant usage on schema public to service_role;
grant insert, select on table public.traveller_profiles to service_role;
grant usage, select on sequence public.traveller_profiles_id_seq to service_role;
comment on table public.traveller_profiles is 'Consent-based trip preferences used by SOS Travellers. No passport, biometric, phone or payment data.';
