create table if not exists public.business_applications (
  id bigint generated by default as identity primary key,
  business_name text not null check (char_length(business_name) between 2 and 100),
  contact_name text not null check (char_length(contact_name) between 2 and 80),
  email text,
  phone text,
  category text not null,
  address text not null check (char_length(address) between 5 and 200),
  languages text[] not null default '{}',
  description text not null check (char_length(description) between 10 and 600),
  website text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.business_applications enable row level security;
grant usage on schema public to service_role;
grant insert, select, update on public.business_applications to service_role;
grant usage, select on sequence public.business_applications_id_seq to service_role;
