-- Three kinds of account and the tools of a business owner.
-- tourist: the default. owner: runs one or more rows of `partners`. boss: the SOS Travellers team.
-- A user cannot change their own role: `authenticated` may only update the columns granted in
-- 202610060001_create_app_users.sql, and `role` is not one of them.
alter table public.app_users add column if not exists role text not null default 'tourist'
  check (role in ('tourist','owner','boss'));

-- A row of `partners` is "the business" its owner manages from the panel and the app.
alter table public.partners add column if not exists owner_id uuid references auth.users (id) on delete set null;
-- Optional link to the business's card in `places`; reviews are keyed by that id (or partner-<id> without one).
alter table public.partners add column if not exists place_id text check (place_id ~ '^[a-z0-9-]{2,64}$');
-- "Serving now" expires by itself so nobody stays open by mistake; null or past = not active.
alter table public.partners add column if not exists active_until timestamptz;
-- [{ "path": "<object in business-photos>", "status": "pending" | "published" | "rejected" }], at most 6.
alter table public.partners add column if not exists photos jsonb not null default '[]'::jsonb;
alter table public.partners add column if not exists address text check (char_length(address) <= 200);
create index if not exists partners_owner_idx on public.partners (owner_id) where owner_id is not null;

-- Owners write promotions; a boss publishes them. Redeemed at the venue: nothing is charged here.
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  partner_id bigint not null references public.partners (id) on delete cascade,
  title text not null check (char_length(title) between 3 and 80),
  description text check (char_length(description) <= 300),
  valid_until date not null,
  status text not null default 'pending' check (status in ('pending','published','rejected')),
  created_at timestamptz not null default now()
);
create index if not exists promotions_partner_idx on public.promotions (partner_id);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  role text not null default 'guest' check (role in ('guest','tourist','owner','boss')),
  message text not null check (char_length(message) between 5 and 600),
  status text not null default 'new' check (status in ('new','read','done')),
  created_at timestamptz not null default now()
);

-- What SOS Travellers gives business owners; written by a boss, shown in the owner panel.
create table if not exists public.owner_benefits (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 80),
  detail text check (char_length(detail) <= 300),
  rank smallint not null default 0,
  status text not null default 'published' check (status in ('draft','published')),
  created_at timestamptz not null default now()
);

alter table public.promotions enable row level security;
alter table public.suggestions enable row level security;
alter table public.owner_benefits enable row level security;
grant select, insert, update, delete on public.promotions, public.suggestions, public.owner_benefits to service_role;
grant usage, select on sequence public.promotions_id_seq, public.suggestions_id_seq, public.owner_benefits_id_seq to service_role;
-- A boss hides or republishes reviews from the panel.
grant update on public.reviews to service_role;

-- Photos of a business. Public read by URL; uploads only through signed URLs issued by api/_routes/owner-photos.ts.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('business-photos', 'business-photos', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

comment on table public.promotions is 'Promociones de un negocio. Solo se muestran con status = published y valid_until vigente.';
comment on table public.suggestions is 'Sugerencias enviadas desde la app o el panel. Las lee el boss.';
comment on table public.owner_benefits is 'Beneficios que SOS Travellers entrega a los dueños de local.';
