create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('radio_taxi','venue','tour','other')),
  name text not null check (char_length(name) between 2 and 100),
  phone text,
  whatsapp text,
  url text,
  region text not null check (region in ('AP','TA','AN','AT','CO','VS','RM','LI','ML','NB','BI','AR','LR','LL','AI','MA')),
  languages text[] not null default '{}',
  note jsonb,
  rank smallint not null default 0,
  status text not null default 'draft' check (status in ('draft','published')),
  created_at timestamptz not null default now()
);

create index if not exists partners_kind_region_idx on public.partners (kind, region) where status = 'published';

alter table public.partners enable row level security;
grant usage on schema public to service_role;
grant insert, select, update, delete on public.partners to service_role;
grant usage, select on sequence public.partners_id_seq to service_role;
comment on table public.partners is 'Colaboradores verificados (radio taxis, recintos, tours). Solo se muestran con status = published. note es {es,en,pt,fr}.';
