create table if not exists public.traveller_preferences (
  id bigint generated by default as identity primary key,
  adults smallint not null check (adults between 1 and 20),
  children smallint not null check (children between 0 and 12),
  trip_days smallint not null check (trip_days between 1 and 90),
  interests text[] not null check (cardinality(interests) between 1 and 10),
  budget text not null check (budget in ('free','low','medium','flexible')),
  pace text not null check (pace in ('relaxed','balanced','intense')),
  preferred_time text not null check (preferred_time in ('morning','afternoon','evening','any')),
  transport text not null check (transport in ('walk','public','car','mixed')),
  connectivity text not null check (connectivity in ('roaming','esim','local_sim','wifi','need_help')),
  preferred_language text not null check (preferred_language in ('es','en','pt','fr')),
  preferred_currency text not null check (preferred_currency in ('CLP','ARS','BRL','USD','EUR','PEN','COP','UYU','GBP','CAD','MXN','AUD')),
  consent_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists traveller_preferences_created_idx on public.traveller_preferences (created_at desc);
alter table public.traveller_preferences enable row level security;
grant usage on schema public to service_role;
grant insert, select on table public.traveller_preferences to service_role;
grant usage, select on sequence public.traveller_preferences_id_seq to service_role;
comment on table public.traveller_preferences is 'Anonymous trip preferences. No name, contact, ID, medical, payment, exact date or location data.';
