create table if not exists public.agent_runs (
  id bigint generated by default as identity primary key,
  agent text not null check (agent in ('events')),
  section text not null check (section in ('contenido','comercial','desarrollo','administracion')),
  status text not null check (status in ('ok','error')),
  started_at timestamptz not null default now(),
  finished_at timestamptz not null default now(),
  summary text check (char_length(summary) <= 600),
  created_count integer not null default 0,
  skipped_count integer not null default 0,
  details jsonb
);

create index if not exists agent_runs_agent_finished_idx on public.agent_runs (agent, finished_at desc);

alter table public.agent_runs enable row level security;
grant usage on schema public to service_role;
grant insert, select on public.agent_runs to service_role;
grant usage, select on sequence public.agent_runs_id_seq to service_role;
comment on table public.agent_runs is 'Registro de cada corrida de un agente. details guarda fuentes revisadas y filas rechazadas. Se lee desde el panel /equipo.';
