create table if not exists public.guide_leads (
  id bigint generated by default as identity primary key,
  guide_id text not null check (guide_id in ('metro-aeropuerto','santiago-noche','santiago-3-dias','pase-sos')),
  email text not null check (char_length(email) between 5 and 160),
  locale text not null check (locale in ('es','en','pt','fr')),
  currency text,
  status text not null default 'new' check (status in ('new','contacted','paid','delivered')),
  created_at timestamptz not null default now(),
  unique (guide_id, email)
);

alter table public.guide_leads enable row level security;
grant usage on schema public to service_role;
grant insert, select, update on public.guide_leads to service_role;
grant usage, select on sequence public.guide_leads_id_seq to service_role;
comment on table public.guide_leads is 'Personas interesadas en una guía exclusiva (src/guides.ts). El correo se guarda en minúsculas.';
